### PR TITLE
Handle rsync installation on read-only distros

### PR DESCRIPTION
**Pull request by Yarboa**
This PR closing this issue psss#988

yum install in RO images, is failing yum to complete
scripts on EDGE/Automotive images.

Updating yum commands to use --installroot=/root/pkg

### CODE REVIEW

**Comment by psss** [comment]
Thanks for the patch. The proposed approach does not seem to be right: It would basically mean that for all provisioned guests the extra `rsync` installation would have to performed, which would be an unnecessary step which would slow down the execution.

We've shortly discussed the use case on today's hacking session and agreed on a rough outline how things could possibly work:

 * The `provision` step should include check for rsync (and make it available if not present)
 * This would/could handle CoreOS use case as well (rpm-ostree install rsync && reboot)

@Yarboa, could you please confirm whether something like this would make sense / be acceptable for your use case?

**Comment by Yarboa** [comment]
> Thanks for the patch. The proposed approach does not seem to be right: It would basically mean that for all provisioned guests the extra `rsync` installation would have to performed, which would be an unnecessary step which would slow down the execution.
> 
> We've shortly discussed the use case on today's hacking session and agreed on a rough outline how things could possibly work:
> 
> * The `provision` step should include check for rsync (and make it available if not present)
Ack
> * This would/could handle CoreOS use case as well (rpm-ostree install rsync && reboot)
> 

@psss  Since there are two options if rpm -q rsync does not exist
1) not installed
2) installed but on different directory, yum need to query it

So code need to check if image is RO or RW is it?
 WDYT? 

I will be grateful for pseudo idea, thanks

> @Yarboa, could you please confirm whether something like this would make sense / be acceptable for your use case?

Yes, it is,

**Comment by thrix** [comment]
> 
> @psss Since there are two options if rpm -q rsync does not exist
> 
> 1. not installed
> 2. installed but on different directory, yum need to query it
> 
> So code need to check if image is RO or RW is it? WDYT?

Couldn't we detect if we need to install rsync by checking existence of `/usr/bin/rsync`?

And detection around if it is an `rpm-ostree` based distro (RO distro) I would make based on `rpm-ostree` command availability, rather then something else? That should provide quite a proof it is ...

WDYT?

> 
> I will be grateful for pseudo idea, thanks
> 
> > @Yarboa, could you please confirm whether something like this would make sense / be acceptable for your use case?
> 
> Yes, it is,

**Comment by Yarboa** [comment]
> > @psss Since there are two options if rpm -q rsync does not exist
> > 
> > 1. not installed
> > 2. installed but on different directory, yum need to query it
> > 
> > So code need to check if image is RO or RW is it? WDYT?
> 
> Couldn't we detect if we need to install rsync by checking existence of `/usr/bin/rsync`?
> 
> And detection around if it is an `rpm-ostree` based distro (RO distro) I would make based on `rpm-ostree` command availability, rather then something else? That should provide quite a proof it is ...

OK we could search for ostree
[  ! -f /usr/bin/ostree ] as an identifier for non tree
[ -f /usr/bin/rsync ] || [ ! -f /usr/bin/ostree ]  || yum install rsync -y
We could go with the regular line, we can change the rpm check for rsync to [ -f /usr/bin/rsync]

In case it return code 127
[ -f /usr/bin/local/rsync ] || yum install --installroot=/root/pkg rsync -y && ln -sf /root/pkg/bin/rsync /usr/local/bin/rsync

I do not like it, but requires two executions of ssh if it is ostree based image
@thrix is it accepted? 

> 
> WDYT?
> 
> > I will be grateful for pseudo idea, thanks
> > > @Yarboa, could you please confirm whether something like this would make sense / be acceptable for your use case?
> > 
> > 
> > Yes, it is,

**Comment by psss** [comment]
What about something like the following?

```bash
rsync --version --quiet || yum install -y rsync || \
    yum install --installroot=/root/pkg -y rsync && ln -sf /root/pkg/bin/rsync /usr/local/bin/rsync
```

This would:

 * do nothing if `rsync` already installed (either `/usr/bin/rsync` or `/usr/local/bin/rsync`)
 * try to install to the default location first and if this fails:
 * install to the custom `installroot` and symlink to `/usr/local/bin`

Seems to me as the most straighforward way from the options brainstormed so far.

**Comment by Yarboa** [comment]
> What about something like the following?
> 
> ```shell
> rsync --version --quiet \
>     || yum install -y rsync \
>     || yum install --installroot=/root/pkg -y rsync && ln -sf /root/pkg/bin/rsync /usr/local/bin/rsync
> ```
> 
> This would:
> 
> * do nothing if `rsync` already installed (either `/usr/bin/rsync` or `/usr/local/bin/rsync`)
> * try to install to the default location first and if this fails:
> * install to the custom `installroot` and symlink to `/usr/local/bin`
> 
> Seems to me as the most straighforward way from the options brainstormed so far.

Thanks, one liner indeed

**Comment by Yarboa** [comment]
> > What about something like the following?
> > ```shell
> > rsync --version --quiet \
> >     || yum install -y rsync \
> >     || yum install --installroot=/root/pkg -y rsync && ln -sf /root/pkg/bin/rsync /usr/local/bin/rsync
> > ```
> > 

After testing it
It is trying on ostree version
```
yum install rsync -y
```
Download packages and then fail on 
RPM: error: can't create transaction lock on /usr/share/rpm/.rpm.lock (Read-only file system
since it is failing to write in RO directory
and then move to the 
```
yum install --installroot=/root/pkg -y rsync   
```
so it is doubles the time of rsync install FYI

> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This would:
> > 
> > * do nothing if `rsync` already installed (either `/usr/bin/rsync` or `/usr/local/bin/rsync`)
> > * try to install to the default location first and if this fails:
> > * install to the custom `installroot` and symlink to `/usr/local/bin`
> > 
> > Seems to me as the most straighforward way from the options brainstormed so far.
> 
> Thanks, one liner indeed

**Comment by psss** [comment]
> so it is doubles the time of rsync install FYI

Ah, I see, so the packages (and package metadata) are fetched twice. So what about checking for the presence of the `rpm-ostree` command as @thrix suggested and picking the suitable install method based on the check result?

**Comment by juanje** [comment]
> 
>     * The `provision` step should include check for rsync (and make it available if not present)
> 
>     * This would/could handle CoreOS use case as well (rpm-ostree install rsync && reboot)
> 

@Yarboa @psss  I like this approach and maybe using the check for `rpm-ostree` for checking OSTree based system (as @thrix suggested). For me is what makes more sense. Most of the OSTree based system (Fedora IoT, RHEL for Edge, RHIVOS...) won't have `yum` or `dnf` installed, so trying to install into an alternative root directory with any of those tools will fail on those systems.

Not sure if that solution (rpm-ostree install rsync && reboot) will work right now on all the provisioners :thinking:

**Comment by Yarboa** [comment]
@psss @thrix 
Is this PR, not planned for review? do you have other PR not dependent with rsync?

**Comment by thrix** [comment]
@Yarboa hi, it is, @psss should be back today ... we will discuss what we decided here. We are not really happy now with the solution, looks kind of hackish :/

**Review by psss — APPROVED** [review]
After our yesterday's discussion it seems the `--installroot` approach seems to be the best way how to make this quickly working. I've slightly updated the fix in adcac66 to check for `rpm-ostree` as `ostree` is installed on regular distros and added the required `--releasever` option. @lukaszachy, @thrix, please, have a look.

**Comment by psss** [comment]
@Yarboa, note that the failure on rawhide is expected, it's podman/selinux problem under investigation.

**Comment by psss** [comment]
@Yarboa, @lukaszachy, @thrix, so are we ok with the current check for `/usr/bin/rpm-ostree` to decide how to perform the `rsync` install? Or any idea of a better way how to detect it's a read-only/coreos distro?

**Review by thrix — APPROVED** [review]
let's try it

**Pull request merged**
