### PR TITLE
RFE: steps/provision/minute: Remove minute plugin.

### PR DESCRIPTION
**Pull request by RHEmployee**
Minute plugin should be downstreamed because it
uses internal infrastructure.

### CODE REVIEW

**Comment by RHEmployee** [comment]
This is still in RFE state.
Packing minute plugin is still in progress.

**Comment by pvalena** [comment]
IMHO this is a step back. Is there no way to upstream the `1minutetip`  implementation instead?

Then we could simply have some config for `minute` internaly, which would point it to right URI/server...

If not because of the "upstream-first" part, consider the benefits lost when the plugin can't be tested along with the upstream changes.

**Comment by RHEmployee** [comment]
Hi! How are you?

Yeah, it's great idea however there is some consensus about: we don't want to open 1minutetip.
I'm pesonaly not against open sourcing 1minutetip. But it's not easy task. 

@psss  Can provide more information about: why is this PR exists.

**Comment by psss** [comment]
Yes, as for now, I believe introducing an internal plugin seems to be the best solution. Currently there is no plan to open source the 1mt server which the functionality of the `minute` plugin depends. A dedicated `tmt-provision-minute` package also solves internal hacks like parsing the url from `1minutetip` script. However this is blocked until the internal plugin is ready and documented. Marked as such.

**Comment by psss** [comment]
For now, we'll just mark the plugin as obsolete and remove after some time. This is handled by #744.

**Pull request closed without merging**
