### PR TITLE
ON HOLD: a very rough sketch of a libvirt backend

### PR DESCRIPTION
**Pull request by t184256**
I've paused implementing it when I've hit #40.

### CODE REVIEW

**Comment by pvalena** [comment]
Vagrant handles the `libvirt` how, so if you keep it this way, it would render mostly all of its functionality useless. Also you're reimplementing what Vagrant does already.

**Comment by t184256** [comment]
@pvalena: that's a valid point. While going raw libvirt could have fewer dependencies and also cover the image creation, it makes sense to focus on vagrant at this point.

**Comment by pvalena** [comment]
@t184256, yes. To be clear, I'm not against a raw Libvirt provision implementation, but there has to be a simple, straightforward, implementation selection mechanism. So user can chose which one to use (I'd call it a `Provider`, maybe?).

**Comment by t184256** [comment]
Isn't it what `tmt run provision --how` is all about?

**Comment by pvalena** [comment]
> Isn't it what `tmt run provision --how` is all about?

Well `how` is TBH a bit misleading here, as I think it should be `where`, like

where? => `localhost`,
where? => `openstack`
where? => `libvirt VM`
where? => `docker`

`how` is that done is a different story. We could implement all of that from scratch, or using some libraries (`go` anyone?), or just relay that implementation to vagrant, by simply creating a `Vagrantfile` with the description what's to be done and running `vagrant up`.

But it's called `how` instead of `where`. And the mechanism by which means to run the `Provisioning` is currently: 
  `localhost`? 
  `yes` => relay to `ProvisionLocalhost`
  `no` => relay to `ProvisionVagrant`

We've also talked about some `Provision` plugin API, but that's probably not in near future.

**Comment by t184256** [comment]
I don't see what's wrong with, e.g., `--how=vagrant.openstack`, `--how=somethingelse.openstack`, and `--how=openstack` deciding what's best for the user that doesn't really care. In my view, `vagrant` is how we run it, and the user should be able to specify that. If `vagrant` has multiple `how`s, it could be extra arguments following `--how=vagrant` or it could be several differently named `how`s with one piece of code behind it.

And what's wrong with the current provisioning API? The fact that the code has to live inside tmt? That's not a big deal to decouple that later.

**Comment by pvalena** [comment]
> I don't see what's wrong with, e.g., `--how=vagrant.openstack`, `--how=somethingelse.openstack`, and `--how=openstack` deciding what's best for the user that doesn't really care.

Firstly let me tell you I do not think it's wrong. It's just not implemented yet in any way, is what I've meant.

In itself doesn't matter which implementation we choose, until the `various implementations` need `different args` / `implement things differently` and are no longer interchargable. Selecting one on runtime (non-deterministically), without user making the decision could potentially 'break' (as we simply cannot try both and choose the one that works). What I'm implying is that specification of `--how=openstack` IMHO should be deterministic and always mean the same implementation (across all of `tmt` versions). Thus, being synonymous to **f.e.** `--how=vagrant.openstack`. **(Meaning there would be no plugin-priority list, or something alike.)**

> In my view, `vagrant` is how we run it, and the user should be able to specify that. If `vagrant` has multiple `how`s, it could be extra arguments following `--how=vagrant` or it could be several differently named `how`s with one piece of code behind it.

Sure, we can expand on the CLI to cover all the use-cases, selecting appropriate keywords, there're multiple ways, and I have no preference (I was merely trying to illustrate the current state and how I percieve it).
Maybe @psss  has already some CLI in mind?

> And what's wrong with the current provisioning API? The fact that the code has to live inside tmt? That's not a big deal to decouple that later.

I don't see it as a problem either. I just meant it should be done if we're to support multiple/custom implemetations for Provisioning.
_Note: Vagrant already supports that via its [Plugins](https://github.com/hashicorp/vagrant/wiki/Available-Vagrant-Plugins), so the idea was to enable usage of users-custom-vagrant-plugin if they wish to, by simply specifying `--how=my-custom-vagrant-plugin`._

**Comment by psss** [comment]
@t184256, do you still plan to work on this? I guess the functionality is now covered by the `testcloud` provision plugin.

**Comment by t184256** [comment]
Agreed, testcloud covers what I was trying to achieve here. No plans for resurrecting this.

**Pull request closed without merging**
