### PR TITLE
Add vagrant to BuildRequires (needed to run tests)

### PR DESCRIPTION
**Pull request by psss**

### CODE REVIEW

**Comment by psss** [comment]
@TomasTomecek, strange that `packit/rpm-build-fedora-rawhide-x86_64` is still `Pending`.

**Comment by psss** [comment]
@TomasTomecek, and after merging the pull request it says "RPM build has started". A bit confusing.

**Comment by TomasTomecek** [comment]
yes, that's annoying - we need some auditing/tracing mechanism in p-s so that we'd be able to resolve issues like these easily

**Pull request merged**
