### PR TITLE
Gracefully handle invalid test output

### PR DESCRIPTION
**Pull request by psss**
Explicitly use utf-8 as encoding and replace all errors.
Add corresponding test coverage.

### CODE REVIEW

**Comment by psss** [comment]
The issue reported by @sopos with traceback similar to this one:

```
    execute
        workdir: /tmp/tmp.G48PE3B6FA/shell.detach/plans/default/execute
        how: shell.detach
        order: 50
            Copy '/usr/lib/python3.8/site-packages/tmt/steps/execute/run.sh' to '/tmp/tmp.G48PE3B6FA/shell.detach/plans/default/execute'.
            Run command './run.sh -v .. shell stdout.log stderr.log'.
        Read file '/tmp/tmp.G48PE3B6FA/shell.detach/plans/default/execute/stdout.log'.
        stdout.log: .D
        Read file '/tmp/tmp.G48PE3B6FA/shell.detach/plans/default/execute/stderr.log'.
    finish
        workdir: /tmp/tmp.G48PE3B6FA/shell.detach/plans/default/finish
            Doing nothing to stop guest 'localhost'.
            Doing nothing to remove guest 'localhost'.
        summary: 0 tasks completed
        status: done
        Write file '/tmp/tmp.G48PE3B6FA/shell.detach/plans/default/finish/step.yaml'.
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tmt/cli.py", line 254, in finito
    context.obj.run.go()
  File "/usr/lib/python3.8/site-packages/tmt/base.py", line 925, in go
    plan.go()
  File "/usr/lib/python3.8/site-packages/tmt/base.py", line 517, in go
    step.go()
  File "/usr/lib/python3.8/site-packages/tmt/steps/execute/__init__.py", line 85, in go
    plugin.go()
  File "/usr/lib/python3.8/site-packages/tmt/steps/execute/detach.py", line 147, in go
    self.show_logs()
  File "/usr/lib/python3.8/site-packages/tmt/steps/execute/detach.py", line 79, in show_logs
    output = self.step.read(log)
  File "/usr/lib/python3.8/site-packages/tmt/utils.py", line 364, in read
    return data.read()
  File "/usr/lib64/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 452: invalid continuation byte
```

This change should fix it for both `tmt` and `detach` executor.

**Comment by sopos** [comment]
just confirming this fix resolves my issue

**Review by thrix — APPROVED** [review]
makes sense to me, we do not want to fail on weird chars ...

**Comment by pvalena** [comment]
LGTM.

**Review by pvalena — APPROVED** [review]
It's fine with me, as it doesn't change any behaviour (IMO this should be default:)).

But in case someone uses different encoding. `utf-8` should probably be just a preset. Those ppl usually come from Windows though :) so we may consider ourselves lucky for the time-being.

**Comment by pvalena** [comment]
_Note: the mentioned (system) setting would be taken from LC_ALL env variable._

**Review by lukaszachy — APPROVED** [review]

**Comment by psss** [comment]
Thanks for the review, guys. Rebased on the latest master and going to merge.

**Pull request merged**
