### PR TITLE
Beakerlib tests need at least beakerlib-1.28

### PR DESCRIPTION
**Pull request by lukaszachy**
TestResults state indicator was introduced in this version and it is
used to validate test result.

### CODE REVIEW

**Comment by lukaszachy** [comment]
Goal is to have fail in prepare phase, e.g.
```
No match for argument: beakerlib >= 1.23

stderr (2/2 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: Unable to find a match: beakerlib >= 1.23

Failed to run command 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@IP rpm -q --whatprovides "rsync" "beakerlib >= 1.23" || dnf install -y "rsync" "beakerlib >= 1.23"'.
```

Instead of error in execution 
```
No result or state found in '/var/tmp/tmt/run-026/..../TestResults'.
```

**Review by jscotka — APPROVED** [review]
LGTM

**Comment by sopos** [comment]
sounds reasonable to me to fail the prepare

**Comment by psss** [comment]
Test `/tests/execute/old` failed:

    out: :: [ 14:00:32 ] :: [  BEGIN   ] :: Running 'rlCheckMakefileRequires 2>&1 | tee output'
    out: :: [ 14:00:32 ] :: [ WARNING  ] :: requirement '1.23' not satisfied
    out: :: [ 14:00:32 ] :: [   LOG    ] :: package 'beakerlib-1.26-1.fc33.noarch'   covers requirement 'beakerlib'
    out: :: [ 14:00:32 ] :: [   LOG    ] :: package 'did-0.17-2.fc33.noarch'         covers requirement 'did'
    out: :: [ 14:00:32 ] :: [   LOG    ] :: package 'tree-1.8.0-5.fc33.x86_64'       covers requirement 'tree'
    out: :: [ 14:00:32 ] :: [   FAIL   ] :: Command 'rlCheckMakefileRequires 2>&1 | tee output' (Expected 0, got 1)

Seems the versioned `require` is not properly handled by `rlCheckMakefileRequires`.

**Comment by lukaszachy** [comment]
Good catch. Investigation and slowly filing beakerlib issue.

**Comment by lukaszachy** [comment]
This PR needs to wait on Beakerlib (and require newer version). Thank you Dalibor for working on Beakerlib fix.

**Comment by jscotka** [comment]
@lukaszachy BTW, now there is issue, that this causes cyclic trouble. whenever you add there had to be at least requires version 1.23, this  NVR requirements will implemented inside version 1.27, so without version 1.27 you are not able to check it an fail early :-)

**Comment by lukaszachy** [comment]
@jscotka And that I meant by ```(and require newer version)```. I'd wait on exact version, we are just assuming it be right in the next version.

**Comment by jscotka** [comment]
> @jscotka And that I meant by `(and require newer version)`. I'd wait on exact version, we are just assuming it be right in the next version.

Ah yep, thanks.

**Comment by psss** [comment]
The fresh `beakerlib-1.27` which contains the fix is in the [release pipeline](https://bodhi.fedoraproject.org/updates/?packages=beakerlib).

**Comment by psss** [comment]
> On second thought - tmt doesn't need beakerlib-1.27. We require 1.23 to parse the result.

Ok, so I kept the `beakerlib-1.23` in the requires. Rebased, ready to merge when tests pass.

**Comment by sopos** [comment]
Apparently there's a need to fix also rlAssertRequired() which was not covered..

**Comment by psss** [comment]
> Apparently there's a need to fix also rlAssertRequired() which was not covered..

So... do you propose to use `1.27` instead?

**Comment by sopos** [comment]
What I'm saying is that I need to release another beakerlib update, so this will be fully covered in 1.28 at earliest.

**Comment by lukaszachy** [comment]
@psss @sopos Should I modify check for `TESTRESULT_STATE` to work with older beakerlib versions as well (read: Allow this value to be missing?)

**Comment by sopos** [comment]
I think it is not crucial at least not at this point. It may be interesting information in connection to export of the results to the Report Portal.

**Comment by psss** [comment]
Ok, I see, so until then `/tests/execute/old` would be failing. Let's wait for `beakerlib-1.28` then. @sopos, do you plan a new `beakerlib` release within a week or so?

**Comment by sopos** [comment]
more likely 2-3 weeks

**Comment by psss** [comment]
Ok, updated the require and commit comment. If needed we can move this to `1.6`.

**Comment by sopos** [comment]
it make much more sense to postpone it to 1.6

**Review by psss — APPROVED** [review]
Looks good. @sopos when do you expect the fresh `beakerlib` could be around?

**Comment by psss** [comment]
The fresh `beakerlib-1.28` is in the [testing](https://bodhi.fedoraproject.org/updates/?packages=beakerlib) repos. We should be able to merge this soon.

**Pull request merged**
