### PR TITLE
When exporting to nitrate link general plan as well

### PR DESCRIPTION
**Pull request by lukaszachy**
Warns about missing component or general plans, however it is not fatal error.

### CODE REVIEW

**Comment by hegerj** [comment]
Why is linking general plan something we want to `export` to do?

**Comment by lukaszachy** [comment]
> Why is linking general plan something we want `export` to do?

TCMS based discovery uses general plans.
If you do not link it to general plan it is not found (so in theory you don't need to export to tcms at all)

**Comment by hegerj** [comment]
New cases ok, but what about exporting already existing cases? Isn't there a usecase where I would want to keep case out of general plan?

**Comment by psss** [comment]
I think it's a reasonable default (same what `tcms-submit` does). Perhaps adding an option to turn that off? But I don't think this use case would be common.

**Comment by hegerj** [comment]
@psss that's my point, you don't (usually) use tcms-submit when changing already existing test case so it doesn't mess with plans, this would try to add general test each time you export

**Comment by lukaszachy** [comment]
OK, so I'll add an option to turn that off.
Once we have global tmt config the default can be configurable.

For me it seems fishy if you do have set value in 'component' but you do not want do link it to its general plan, but wharever

**Comment by lukaszachy** [comment]
Now with `--no-general ` option

**Pull request merged**
