### PR TITLE
WIP: add fingertip provisioner

### PR DESCRIPTION
**Pull request by t184256**
Does execute successfully for me, but testing on a clean machine would be welcome.

Requires [fingertip](https://github.com/t184256/fingertip) >=0.2.1, which should be easier now that it has a [copr](https://copr.fedorainfracloud.org/coprs/asosedkin/fingertip).

### CODE REVIEW

**Comment by psss** [comment]
Thanks for the new plugin. I've played with it a bit and ran into the following exception:

```
Traceback (most recent call last):
  File "/home/psss/git/tmt/tmt/base.py", line 396, in go
    step.go()
  File "/home/psss/git/tmt/tmt/steps/provision/__init__.py", line 61, in go
    guest.go()
  File "/home/psss/git/tmt/tmt/steps/provision/fingertip_.py", line 41, in go
    .apply('ansible', 'package', name='rsync', state='present')
  File "/home/psss/.virtualenvs/tmt/lib/python3.7/site-packages/fingertip/machine.py", line 127, in apply
    fingertip_last_step)
  File "/home/psss/.virtualenvs/tmt/lib/python3.7/site-packages/fingertip/machine.py", line 175, in _cache_aware_apply
    m = func(self, *args, **kwargs)
  File "/home/psss/.virtualenvs/tmt/lib/python3.7/site-packages/fingertip/plugins/ansible.py", line 62, in main
    _ansible(m, '-m', module, '-a', ' '.join(module_args))
  File "/home/psss/.virtualenvs/tmt/lib/python3.7/site-packages/fingertip/plugins/ansible.py", line 35, in _ansible
    f'ansible_ssh_private_key_file={m.ssh.key_file}']
  File "/home/psss/.virtualenvs/tmt/lib/python3.7/site-packages/fingertip/plugins/backend/qemu.py", line 417, in key_file
    s = os.stat(key_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/psss/.virtualenvs/tmt/lib/python3.7/site-packages/ssh_key/fingertip'
```

Any additional configuration needed? I used the latest version from `pip`.

**Comment by t184256** [comment]
Ouch, this is a Python packaging issue. Meanwhine, could you try an RPM or specifying a path to checkout with PYTHONPATH?

**Comment by t184256** [comment]
I hope it is fixed now in v0.2.3, but I'd still go for an RPM for now (native dependencies, VM image cleanup job, more tested).

**Comment by t184256** [comment]
OK, sorry, the RPM is wrong too =) Will fix.

**Comment by t184256** [comment]
0.2.4 (copr) should work better

**Comment by psss** [comment]
Thanks for the fix. Tested with `fingertip-0.2.4-1.g0c72912.fc31.noarch` and works fine. It's super quick! Beautiful! :-)

**Comment by t184256** [comment]
Wow, didn't expect it to start working that soon =)

It can be made even faster if I make it cache the prepare step, but it's pretty unclear to me how to cache it properly, as in, when to invalidate it. Got any suggestions? Can that 'specify-the-same-run' interface be used here? How?

**Comment by psss** [comment]
@t184256, do you plan to convert the code into a dynamic provision plugin? In other words rebasing on the latest master?

**Comment by t184256** [comment]
Yes, but I didn't get to it yet.

**Comment by psss** [comment]
@t184256, do you plan to work on this in the near future?

**Comment by t184256** [comment]
Not in the near future, unfortunately.

**Comment by psss** [comment]
Ok, let's re-open this once you have time.

**Pull request closed without merging**
