### PR TITLE
Allow creation of nitrate cases when exporting

### PR DESCRIPTION
**Pull request by hegerj**
Added option --create which will create testcase in nitrate if it
doesn't exist.
Implements #117.

### CODE REVIEW

**Comment by hegerj** [comment]
@psss There are couple of TODOs left in the code, could you please check those?

**Comment by hegerj** [comment]
Because of the second function that needed nitrate I moved its import outside which brought back the import problem (thats why the checks are failing I believe).
Question is what to do about it.
1) move the import back into function `export_to_nitrate()` and import nitrate in `create_nitrate_case()` as well
2) move the import back into function `export_to_nitrate()` and pass the nitrate as parameter to `create_nitrate_case()`
3) rework `create_nitrate_case()` to not need nitrate and handle test case creation in `export_to_nitrate()`

What do you think/do you have different solution? Neither of those I proposed look good to me.

**Comment by psss** [comment]
I would suggest to import in both functions. Python does the import only once so it basically does not matter.

**Comment by psss** [comment]
Thanks for writing support for test case creation.
Adjusted in 3f8c604 and going to merge if tests pass.

**Pull request merged**
