### PR TITLE
Support environment variables from YAML files

### PR DESCRIPTION
**Pull request by happz**
With increasing number of `-e` options, tmt command-line might easily
become quite unreadable. It might be more convenient to save the
variables into a YAML file, and let tmt load the variables from given
file.

`--environment KEY=VALUE` now also accepts `--environment @foo.yaml` -
if the given value starts with `@` character, the value is treated as a
YAML filepath, and variables are loaded from this file.

* [x] update help of `--environment`
* [x] add `environment_to_dict` instead of extending `shell_to_dict`
* [x] switch relevant call sites to `environment_to_dict`
* [x] add test

### CODE REVIEW

**Comment by happz** [comment]
Kindly asking for a review - NOT tested, yet, I'm interested in finding out whether this approach would be acceptable - familiar with Ansible's `--extra-vars @foo.yaml`, I decided to use the same way, instead of adding new option (like `--environment-file foo.yaml`).

* Should JSON input be supported as well?
* Is this the correct place where to add this functionality? It seems to me like `shell_to_dict` is handling `--environment`, extending its functionality seems to me like a good place.

**Comment by psss** [comment]
Thanks for the improvement, @happz. Looks fine to me. I like the approach with the `@` prefix for files. Regarding the placement: It would be probably better to introduce a new function as parsing variables from a `yaml` file is not a `shell_to_dict` conversion (not converting from the shell `VAR=VAL` format). As far as `json` is concerned, I don't think it's necessary for now. Please, also update the `--help` message and add at least a simple test for this (or extend the `/tests/core/env` one). Thanks.

**Comment by happz** [comment]
> Regarding the placement: It would be probably better to introduce a new function as parsing variables from a `yaml` file is not a `shell_to_dict` conversion (not converting from the shell `VAR=VAL` format).

Do you mean introducing a brand new function to handle this "environment_to_dict" conversion? Or would renaming `shell_to_dict` do? It seems to me it's used to handle `-e` option and nothing else. Or, I could preserve `shell_to_dict`, and clone my changes into a brand new function and use this one to handle `-e` option.

> Please, also update the `--help` message and add at least a simple test for this (or extend the `/tests/core/env` one). Thanks.

Will do, thanks.

**Comment by psss** [comment]
The `shell_to_dict` function is also used in `tmt/convert.py`. It would not break it but let's prevent any possible confusion and introduce a new function `environment_to_dict` to handle this (which will call `shell_to_dict` for handling the `VAR=VAL` case).

**Comment by happz** [comment]
Understood, thanks.

**Comment by psss** [comment]
Thanks for the update, @happz. Looks good. I've rebased the code on the latest master, squashed and added a couple of style changes.

**Pull request merged**
