### PR TITLE
Enough of dreaming, let's go to the forest! :)

### PR DESCRIPTION
**Pull request by psss**
It seems that most of our outlined dreams have already become
true. It's time to forget about dreams and put together a nice
guide which would help new users to walk through the features
which are eagerly waiting for them. What about a couple of
bite-size kind-of stories which will demonstrate essential
features on tangible examples?

In addition to writing The First Steps section and removal of the
dreams pages I've moved the only unfulfilled dream to the stories
and fixed a trivial typo in the README.

### CODE REVIEW

**Review by lukaszachy — APPROVED** [review]
LGTM, Guide is very nice.

**Review by FrNecas — APPROVED** [review]
Nice write-up

**Comment by psss** [comment]
Great! Thanks for the quick review.

**Comment by thrix** [comment]
nice, I like it! just too late to the review party :balloon:

**Pull request merged**
