### PR TITLE
Remove the hack for the old cruncher executor

### PR DESCRIPTION
**Pull request by psss**
Disable `/tests/discover/libraries` by default as it needs full
virtualization. Use `tmt --context how=full run` to include it.
Document how to run the default and full test coverage.

### CODE REVIEW

**Comment by psss** [comment]
@thrix, @lachmanfrantisek, @jpopelka: Smoke test on the stage finished with:

 *  maximum recursion depth exceeded while calling a Python object
 *  Tests failed ... (a couple of tests [timeouted](http://artifacts.dev.testing-farm.io/452e42d5-7afd-4f06-b800-87d4f8b95b3a/work-advancedkNf_HQ/tmt-run.log))
 *  Pending — Tests have been submitted ...

The last two jobs are running for quite a long time.

**Review by lukaszachy — APPROVED** [review]
LGTM

**Comment by psss** [comment]
Thanks for the review, @lukaszachy. All tests passed on fedora 32/33, good enough for now!

**Comment by thrix** [comment]
mmkay, centos should be better now.

**Comment by thrix** [comment]
ups, merged

**Pull request merged**
