### PR TITLE
Fix blocking read in Common.run

### PR DESCRIPTION
**Pull request by lukaszachy**

### CODE REVIEW

**Comment by lukaszachy** [comment]
@psss This fixes my 'xdg-open' not returning issue. I'm not really happy to report green on timeout but I couldn't think of anything better.

**Comment by psss** [comment]
Sorry, haven't noticed this is filed against the `report-html` branch.

**Comment by pvalena** [comment]
This looks really complicated :) I love it.

Some questions come to my mind though:

 - Why would `xdg-open` block? I regularly run it everywhere and it did never block AFAIR.
   - Leaving the stdout could maybe cause this issue. Will this help?  `xdg-open file:///my/path/index.html >/dev/null`
   - If not, what would happen if it was run like this? `nohup xdg-open file:///my/path/index.html &`
 - What about https://docs.python.org/3/library/webbrowser.html ?

**Comment by lukaszachy** [comment]
@pvalena Thank you for webbrowser idea. I have created #455 with that. This PR will be about blocking Common.run

**Comment by lukaszachy** [comment]
Recap of issue this is trying to fix:
On my fedora-33 when I had no firefox running following  didn't finish (=continue on next line) until I manually closed newly opened window:
`tmt.utils.Common().run('xdg-open /var/tmp/tmt/run-018/DEMO/report/default/index.html', timeout=2)` 
Note there is `timeout=2` which successfully killed the process, however execution was blocked either on `select.select(descriptors, [], [])` in process.poll() loop OR on `for line in process.stdout.readlines()`

**Comment by torsava** [comment]
The change looks good to me!

**Review by psss — APPROVED** [review]
Looks good. Verified it does not break anything with the complete test coverage.

**Comment by psss** [comment]
Rebased and merged. Thanks much for investigating this, @lukaszachy!

**Pull request merged**
