### PR TITLE
Execute: Add run.sh for running the tests on guest.

### PR DESCRIPTION
**Pull request by pvalena**
**Feel free to merge.**

### CODE REVIEW

**Comment by pvalena** [comment]
How about this?  [ `actually works ;)` ]
```
$ pwd
/var/tmp/tmt/run-122/plans/smoke
$ cat discover/tests.yaml
/one/tests/docs:
    duration: 5m
    path: /one/tests/docs
    test: ./test.sh
/one/tests/ls:
    duration: 5m
    path: /one/tests/
    test: ./test.sh
$ cat discover/one/tests/test.sh
#!/bin/bash

echo "sample STDOUT"
echo "sample STDERR" >&2
exit 87
$ cat discover/one/tests/docs/test.sh
#!/bin/bash

echo "sample STDOUT 2"
echo "sample STDERR 2" >&2

exit 88
$ ls execute/
run.sh
$ execute/run.sh -v `pwd` shell
 /var/tmp/tmt/run-122/plans/smoke $ main shell < discover/tests.yaml
 > /one/tests/docs:
 >     duration: 5m
 >     path: /one/tests/docs
 >     test: ./test.sh
 > > runtest /one/tests/docs ./test.sh /one/tests/docs 5m
 > > cd '/var/tmp/tmt/run-122/plans/smoke/discover/one/tests/docs' && timeout '5m' ./test.sh 1>stdout.log 2>stderr.log 0>exitcode.log
 > > stdout.log:
sample STDOUT 2
 > > stderr.log:
sample STDERR 2
 > > exitcode.log:
88
 > /one/tests/ls:
 >     duration: 5m
 >     path: /one/tests/
 >     test: ./test.sh
 > > runtest /one/tests/ls ./test.sh /one/tests/ 5m
 > > cd '/var/tmp/tmt/run-122/plans/smoke/discover/one/tests' && timeout '5m' ./test.sh 1>stdout.log 2>stderr.log 0>exitcode.log
 > > stdout.log:
sample STDOUT
 > > stderr.log:
sample STDERR
 > > exitcode.log:
87

$ # without verbose:
$ execute/run.sh `pwd` shell
FF
$ sed -i 's/87/0/' discover/one/tests/test.sh
$ execute/run.sh `pwd` shell
F.

```

... `env -i $YOUR_PASSED_ENV` should work also :) but I did not thest that.

TODO: beakerlib

**Comment by pvalena** [comment]
@psss  btw. your generated `tests.yml` for `smoke` is broken, as it contains `/one/tests/ls` as path, wich does not exist.

**Comment by psss** [comment]
Thanks. Tested, works as expected. Merging.

**Comment by psss** [comment]
Wrong test path fixed in 925fef4.

**Pull request merged**
