### PR TITLE
Remove hardcoded ansible_python_interpreter=auto

### PR DESCRIPTION
**Pull request by fernflower**
This would make tmt respect user defined ansible_python_interpreter that
might be set per task.

Closes: https://github.com/psss/tmt/issues/729

### CODE REVIEW

**Comment by psss** [comment]
Thanks, looks good. Could you possibly add at least a simple tier 3 test `/tests/prepare/ansible` which would verify the `ansible` method works fine against both latest fedora and centos images? For some inspiration you can have a look at [/tests/prepare/require](https://github.com/psss/tmt/tree/master/tests/prepare/require) or [/tests/run/worktree](https://github.com/psss/tmt/tree/master/tests/run/worktree).

**Comment by fernflower** [comment]
> Thanks, looks good. Could you possibly add at least a simple tier 3 test `/tests/prepare/ansible` which would verify the `ansible` method works fine against both latest fedora and centos images? For some inspiration you can have a look at [/tests/prepare/require](https://github.com/psss/tmt/tree/master/tests/prepare/require) or [/tests/run/worktree](https://github.com/psss/tmt/tree/master/tests/run/worktree).

Is having those tests written with beakerlib a requirement? I have never used it. 
What exactly should the test check?

**Comment by psss** [comment]
> Is having those tests written with beakerlib a requirement? I have never used it.

Not exactly a requirement, but probably good to keep consistency. And it brings some nice features such as logging/asserts. `tmt test create -t beakerlib /tests/prepare/ansible` will give you a quick start. Not much to learn once you see the skeleton.

> What exactly should the test check?

For start I would just verify that applying a simple ansible playbook during the `prepare` step works fine across `centos:7`, `centos:8` and `fedora` container image. I can write the test. Let me know what you would prefer.

**Comment by psss** [comment]
The two test failure caused by a network glitch, let's /packit test once more.

**Pull request merged**
