### PR TITLE
Require a newer fmf which supports storing data

### LINKED ISSUE #238: `tmt tests export --nitrate --create` removes virtual case from fmf file
At first I had main.fmf like this
```yaml
summary: Some text
contact: my@email.com
component: [ package ]
test: ./test.sh
environment:
    FOO: bar

/additional:
    environment:
        key: value
```
I've run `tmt tests export --nitrate --create` so two cases are created in the nitrate.
But tmt removed virtual case from the fmf file and created just first case (and didn't link it to general plan)
After execution the main.fmf is as following:
```yaml
summary: Some text
contact: my@email.com
component: [ package ]
test: ./test.sh
environment:
    FOO: bar
extra-nitrate: TC#0607295
```

### PR DESCRIPTION
**Pull request by psss**
Using the new fmf feature to store modified metadata to disk
should fix issue with removed virtual cases during export.

Resolves #238.

### CODE REVIEW

**Review by jscotka — APPROVED** [review]
LGTM

**Review by lukaszachy — COMMENTED** [review]
Don't we need 0.16? `Use a deep copy when storing raw node data`

**Comment by psss** [comment]
Good point, version updated.

**Review by lukaszachy — APPROVED** [review]

**Comment by psss** [comment]
Now let's wait until the fresh `fmf` reaches the stables repos.

**Pull request merged**
