### PR TITLE
Do not expand the process environment variables

### PR DESCRIPTION
**Pull request by psss**
Expanding variables from the tmt process could reveal sensitive
information such as user tokens. Let's substitute only explicitly
provided variables in the plan and the `--environment` option.

### CODE REVIEW

**Review by lukaszachy — APPROVED** [review]

**Comment by psss** [comment]
@FrNecas, please have a look as well. For a bit more context see also the following [discussion](https://github.com/psss/tmt/pull/795#discussion_r679776161).

**Review by FrNecas — APPROVED** [review]
Makes sense, thanks for spotting and fixing this!

**Pull request merged**
