### PR TITLE
Code-style improvements according to PEP8

### PR DESCRIPTION
**Pull request by FrNecas**
While replacing PyYAML with ruamel.yaml, I noticed that some parts our code don't comply with PEP8, mainly import order and blank lines around classes/functions. We embrace PEP8 compliance in our contribution guide, so lets try to follow it ourselves :)

This PR fixes:
 - group imports into 3 categories (standard libraries, third party libraries, local imports) as described in https://www.python.org/dev/peps/pep-0008/#imports (also remove unused imports)
 - surround top-level classes and functions with 2 blank lines as described in https://www.python.org/dev/peps/pep-0008/#blank-lines

### CODE REVIEW

**Comment by psss** [comment]
Thanks for looking into this! Makes sense to me to clean this up. What about also putting the import lines in alphabetic order? As for now they are in semi-random order, sometimes just to make a nice shape ;-)

**Comment by FrNecas** [comment]
Yeah, I thought about ordering them alphabetically too. Even though it is not specified in PEP8, I think we should try to follow it, it makes the imports a bit more organized. On the other hand, it may be hard to keep up with this practice when new imports are being added but for now, lets try to organize them nicely. I will add one more commit with alphabetic ordering ;)

**Comment by FrNecas** [comment]
Should be fixed, hope I didn't miss anything. Unfortunately, this PR is probably going to cause some merge conflicts in other PRs but there is probably not much we can do about it...

**Comment by thrix** [comment]
@FrNecas @psss what about if we would rather use `black` and `isort` for these things?

Seems like automated solution, we can add it to `pre-commit` and do not care anymore?

**Comment by FrNecas** [comment]
That would be nice to keep code style consistent and make it easier to contribute. I haven't worked with `isort` yet but it seems like a nice tool. As for `black`, sometimes the formatting seems a little weird to me (even though it complies with PEP8) but perhaps that configurable?

**Comment by thrix** [comment]
@FrNecas something is configurable 

> That would be nice to keep code style consistent and make it easier to contribute. I haven't worked with `isort` yet but it seems like a nice tool. As for `black`, sometimes the formatting seems a little weird to me (even though it complies with PEP8) but perhaps that configurable?

Black is not much configurable, it is opinionated. But I consider it still better than to review styling problems of the code :D

**Comment by psss** [comment]
Have no experience with `black`. Depends if it generates a beautiful output :-) Which is highly relative, I know... To further brainstorm possible options, what about enabling some (configurable) style checking bot for the pull requests? Perhaps [pep8speaks](https://github.com/OrkoHunter/pep8speaks)?

**Comment by jscotka** [comment]
@thrix @FrNecas I've created PR to use `precommit` with black inside FMF yesterday
https://github.com/psss/fmf/pull/130 
so maybe it could be consolide inside FMF and TMT in same way.

**Comment by psss** [comment]
I have shortly experimented with `black` and I'm afraid I have a couple problems with it:

First of all, it seems it forces to always use a hanging parenthesis which are not aligned with the included block. I find these parenthesis very confusing (although pep8 allows them as well).

```python
raise tmt.utils.SpecificationError(
    f"Missing test name in '{self.step.plan.name}'."
)
```

This sometimes results into many extra lines: Here's an example before:

```python
sorted_expect = sorted(enumerate_content(concatenate_headings_content((
    '<h2>Expect</h2>',
    '<h2>Result</h2>',
    '<h2>Expected Result</h2>'))) + sorted_test)
```

And after:

```python
sorted_expect = sorted(
    enumerate_content(
        concatenate_headings_content(
            (
                '<h2>Expect</h2>',
                '<h2>Result</h2>',
                '<h2>Expected Result</h2>',
            )
        )
    )
    + sorted_test
)
```

Also I don't see much benefit in the one-parameter-per line approach:

```python
def show(
    context, implemented, verified, documented, covered,
    unimplemented, unverified, undocumented, uncovered, **kwargs):
    """
    Show story details.

    Regular expression can be used to filter stories by name.
    Use '.' to select stories under the current working directory.
    """
    tmt.Story._save_context(context)
    for story in context.obj.tree.stories():
        if story._match(implemented, verified, documented, covered,
                unimplemented, unverified, undocumented, uncovered):
            story.show()
            echo()
```

and after:

```python
def show(
    context,
    implemented,
    verified,
    documented,
    covered,
    unimplemented,
    unverified,
    undocumented,
    uncovered,
    **kwargs,
):
    """
    Show story details.

    Regular expression can be used to filter stories by name.
    Use '.' to select stories under the current working directory.
    """
    tmt.Story._save_context(context)
    for story in context.obj.tree.stories():
        if story._match(
            implemented,
            verified,
            documented,
            covered,
            unimplemented,
            unverified,
            undocumented,
            uncovered,
        ):
            story.show()
            echo()
```

And one more: Three lines before:

```python
    output = self.run(
        ['git', 'log', '--format=', '--stat', '--name-only',
        f"{modified_ref}..HEAD"], cwd=testdir, shell=False)[0]
```

12 lines after:

```python
    output = self.run(
        [
            'git',
            'log',
            '--format=',
            '--stat',
            '--name-only',
            f"{modified_ref}..HEAD",
        ],
        cwd=testdir,
        shell=False,
    )[0]
```

The following is also confusing:

```python
TEST_METADATA['shell'] = """
summary: Concise summary describing what the test does
test: ./test.sh
""".lstrip()
```

And after:

```python
TEST_METADATA[
    'shell'
] = """
summary: Concise summary describing what the test does
test: ./test.sh
""".lstrip()
```

**Comment by psss** [comment]
Tried `autopep8` using the following options:

    autopep8 --recursive --in-place --aggressive --aggressive --hang-closing tmt

The output looks much better to me.

**Comment by jscotka** [comment]
@psss yep, it is sometimes confusing it breaks some lines more than it needs, but your some of your examples what are bad are sometimes good for someone; eg this
```
def show(
    context,
    implemented,
    verified,
    documented,
    covered,
    unimplemented,
    unverified,
    undocumented,
    uncovered,
    **kwargs,
):
```
is better for me than, to have it splitted to 2  lines. But it is more less personal preference.

**Comment by FrNecas** [comment]
@psss Hi, sorry I missed your question on IRC today. I think the headings in CLI that you mentioned are nice and useful. With so many commands and subcommands, it can get confusing keeping track of what belongs to what when searching in the code. This way, it's apparent where a new command starts (This is especially apparent with plans and stories). So I'd personally keep it. But this is one is definitely about personal taste :)

**Comment by psss** [comment]
Ok, agreed, makes sense.

**Review by psss — APPROVED** [review]
Thanks much for the cleanup. I've just modified two empty lines to be consistently before the comment heading if present. Also squashed both `import` related commits into one.

**Pull request merged**
