### PR TITLE
An example plugin skeleton

### PR DESCRIPTION
**Pull request by RHEmployee**
WIP and first draft of how tmt plugin example skeleton should look a like.

### CODE REVIEW

**Comment by RHEmployee** [comment]
MR is related to:
https://github.com/psss/tmt/issues/760

**Comment by FrNecas** [comment]
Looks like a good start. I'd personally keep the example plugins away from the real plugins and just leave them as a code snippet in documentation, seeing an example plugin when running `tmt run provision --help` would slightly confuse me as it does completely nothing other than printing stuff. But I think printing what's being done is a good start, it provides boilerplate code that one can easily paste into a file, run it and see which methods are called at which times and why. The example discover plugin could IMHO use some work and a bit more realistic example. I didn't go through the code very thoroughly since this is a draft but I'd also avoid using `"""` strings inside a function (with the exception of a docstring) and use a comment instead.

**Comment by psss** [comment]
Agree that it would be better to store the example code elsewhere to prevent confusion. Including the whole plugin code on the [contribute](https://tmt.readthedocs.io/en/latest/contribute.html) page would probably make it a bit too large. What about creating a new `plugins` folder under [examples](https://github.com/psss/tmt/tree/master/examples) and link from the docs there? Optionally we could also introduce a subpages for the contribute section and have a dedicated page for plugins there. Another good candidate for a separate subpage are **Classes** which could host both Class Structure and Essential Classes.

**Comment by RHEmployee** [comment]
Update: I forgot about connection with:
https://github.com/psss/tmt/issues/760
which is not assigned to this mr for now :).

**Comment by RHEmployee** [comment]
> Looks like a good start. I'd personally keep the example plugins away from the real plugins and just leave them as a code snippet in documentation, seeing an example plugin when running `tmt run provision --help` would slightly confuse me as it does completely nothing other than printing stuff. But I think printing what's being done is a good start, it provides boilerplate code that one can easily paste into a file, run it and see which methods are called at which times and why. The example discover plugin could IMHO use some work and a bit more realistic example. I didn't go through the code very thoroughly since this is a draft but I'd also avoid using `"""` strings inside a function (with the exception of a docstring) and use a comment instead.

Ok. Moved to another directory and replaced """ with # comments.

**Comment by RHEmployee** [comment]
Just idea: what about some example metadata?
Where it should be stored? Looks like:
tmt/plans/provision
is good place even for example metadata.

**Comment by psss** [comment]
Please, try to `make docs` locally. There is a couple of warnings which cause the `/plans/install/docs` to fail.

**Comment by RHEmployee** [comment]
> Please, try to `make docs` locally. There is a couple of warnings which cause the `/plans/install/docs` to fail.

Thanks. I found online way how to check if text is correctly formated :).

**Review by psss — APPROVED** [review]
Thanks for preparing the plugin examples and documentation. I've adjusted it a bit in 18f4a9b. Should now be ready for merging.

**Pull request merged**
