### PR TITLE
Make minute plugin internal

### PR DESCRIPTION
**Pull request by lukaszachy**
We should find a way how to link internal documentation.

CC: @RHEmployee

### CODE REVIEW

**Comment by lukaszachy** [comment]
@psss LGTM.

**Review by FrNecas — APPROVED** [review]
LGTM. I guess we can close this https://github.com/psss/tmt/pull/654 for now? I suppose we are going to keep the minute plugin as obsolete for some time before deprecating it completely.

**Comment by psss** [comment]
> I guess we can close this #654 for now?

Yes, we'll keep the obsolete plugin for a couple of weeks/months. I will just disable the warning for now, until the internal plugin is completely ready, so that we do not bother user too early.

**Review by psss — APPROVED** [review]
Thanks. Squashed and moved warning to #745.

**Comment by psss** [comment]
The two failures on `fedora-32` and `epel-8` seem to be caused by a `podman` issue. Access to files and directories seems to be broken:

```
podman run -it --rm fedora:34
[root@8b06074e6877 /]# cd /tmp
[root@8b06074e6877 tmp]# echo content > file
[root@8b06074e6877 tmp]# cat file
content
[root@8b06074e6877 tmp]# stat file
  File: file
  Size: 8         	Blocks: 8          IO Block: 4096   regular file
Device: 25h/37d	Inode: 266289      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-04-28 17:09:21.558160767 +0000
Modify: 2021-04-28 17:09:19.215143672 +0000
Change: 2021-04-28 17:09:19.215143672 +0000
 Birth: 2021-04-28 17:09:19.214143665 +0000
[root@8b06074e6877 tmp]# [ -r file ] && echo readable
[root@8b06074e6877 tmp]# 
```

But after updating the `fedora-32` box the issue is fixed. @thrix, it seems that we'll need to update the testing farm images. Merging.

**Comment by martinpitt** [comment]
Sounds like good old https://bugzilla.redhat.com/show_bug.cgi?id=1900021 ? The usual workaround is `podman run --security-opt seccomp=unconfined`

**Pull request merged**
