### PR TITLE
base.Plan: Fix gates/artifacts conversion to list

### PR DESCRIPTION
**Pull request by vinzenz**
Previously the code would crash with a use before assignment, as for the
variables the reference to self has been missing.
This patch fixes this oversight.

Signed-off-by: Vinzenz Feenstra <vfeenstr@redhat.com>

### CODE REVIEW

**Review by lukaszachy — APPROVED** [review]

**Comment by lukaszachy** [comment]
Thank you very much for your PR, @vinzenz. Would you mind editing your commit message according to https://tmt.readthedocs.io/en/latest/contribute.html#commits ? E.g. to `Fix gates/artifacts conversion to list`

**Review by thrix — APPROVED** [review]
LGTM

**Review by psss — CHANGES_REQUESTED** [review]
Thanks for fixing this! Hmmm, the `artifact` field has been obsoleted and removed some time ago in 8329db0421e902272a9606b4d97085aa40c427a3. I guess these remnants should be completely removed.

**Review by psss — APPROVED** [review]
Thanks for the changes. I've added a small adjustment to sync with the specification.

**Pull request merged**
