### PR TITLE
Require correct testcloud version in setup.py

### PR DESCRIPTION
**Pull request by FrNecas**
https://github.com/psss/tmt/pull/827 only changed it inside specfile but not in setup.py which is useful for running the latest tmt version.

### CODE REVIEW

**Comment by FrNecas** [comment]
Looks like we will have to use `0.6.1` (see https://github.com/psss/tmt/issues/837), I will update the required version in this PR once it's released.

**Comment by psss** [comment]
The bodhi update has reached stable repos. Both `setup.py` and `tmt.spec` updated to require `0.6.1`.

**Review by psss — APPROVED** [review]
Thanks for catching this!

**Comment by psss** [comment]
The `epel-8` job passed, rawhide failure irrelevant, merging.

**Pull request merged**
