### PR TITLE
Let's debug the "Could not resolve host" issue!

### PR DESCRIPTION
**Pull request by psss**
@thrix, here's the pull request with added `cat /etc/resolv.conf` to investigate...

### CODE REVIEW

**Comment by psss** [comment]
@thrix, nice, so we've caught a [double failure](http://artifacts.dev.testing-farm.io/b369840d-c641-47fb-9b81-2e6b6033ea14/) during the last run. Unfortunately, the `resolv.conf` check was too late. What's interesting is that the failure occured during the [package installation](http://artifacts.dev.testing-farm.io/b369840d-c641-47fb-9b81-2e6b6033ea14/guest-setup-83c6e82c-3a3f-4b94-8331-02af4ce93591/artifact-installation-83c6e82c-3a3f-4b94-8331-02af4ce93591/0-Download-copr-repository.txt) as well.

**Comment by psss** [comment]
We've caught another failure, but there are [no details](http://artifacts.dev.testing-farm.io/bc92b829-01b5-4367-b7b6-0da2db2c970a/).

**Comment by psss** [comment]
Catched another [failure](http://artifacts.dev.testing-farm.io/e27d9f6a-7e7e-4eb5-b8fb-0f2c88464f3b/), the `resolv.conf` content:

    search us-east-2.compute.internal
    nameserver 172.31.0.2

**Comment by psss** [comment]
Everything's green. Let's try once more: /packit test

**Comment by psss** [comment]
One fresh [failure](http://artifacts.dev.testing-farm.io/90cbe379-dbff-4444-a7e8-a91d749a1267/) caught on Fedora 34.

**Comment by psss** [comment]
Issue [reproduced](http://artifacts.dev.testing-farm.io/3d3fea04-c583-4674-989e-5ffbfd6134b0/) with 5 retries, name servers were `8.8.*.*`.

**Comment by psss** [comment]
Everything green.
/packit test

**Comment by lukaszachy** [comment]
Is this still necessary? If so - could it be a draft and rename to something more distinct to normal PR names? E.g. 'DO NOT CLOSE - debugging "Could not resolve host"'

**Comment by psss** [comment]
Recently, the issue stopped occuring frequently. Let's close for now and re-open if needed for further investigation.

**Pull request closed without merging**
