### PR TITLE
Implement variables for storing logs and artifacts

### PR DESCRIPTION
**Pull request by psss**
Introduce `TMT_TEST_DATA` and `TMT_PLAN_DATA` variables which can
be used during `prepare`, `execute` and `finish` step for storing
artifacts such as logs into a directory which is pulled back from
the guest for further inspection.

This change also fixes regression introduced by ec1d88b which
caused the `results.yaml` file to be overridden by empty results
file fetched back from the guest by pulling only selected
directories instead of the whole plan workdir.

It should also cover #1011 by pulling logs only if any `prepare`,
`execute` or `finish` plugin has been executed. However, a proper
fix which would keep track of the pushed state and ensure that the
whole workdir content is pushed only once is still needed.

### CODE REVIEW

**Comment by lukaszachy** [comment]
How likely is the conflict on "output.txt" name? I'm concerned about situation when originally you have in test existing redirect to output.txt and since pull changed you realise you need to store it in TMT_TEST_DATA directory.
Nothing complains so you don't realise that you overwrite test output until late. In other words for existing `command |tee output.txt` can't just `command |tee $TMT_TEST_DATA/output.txt` but to rename output file as well.

**Comment by psss** [comment]
> How likely is the conflict on "output.txt" name?

Hm, that collision might happen. On the other hand I would not expect this to be frequent. One possible solution would be to provide a clean subdirectory under `execute/test/name/` but that would mean an extra click to get to the additional logs. For now I'd prefer to have all logs in a single directory. If the need pops up in the future we can always introduce the subdirectory, tests would not be broken as the `TMT_TEST_DATA` variable would still work. What do you think?

**Comment by lukaszachy** [comment]
I think I understand what you say by extra click but tmt stores too many own files... It's quite difficult to see what files I stored intentionally and which are from tmt. Maybe extra subdir will make it more clear to browse locally (in html presentation it doesn't matter - one will click urls anyway)

```
/var/tmp/tmt/run-001
├── log.txt
├── repro
│   └── plan
│       ├── data
│       │   ├── from_finish
│       │   ├── from_prepare
│       │   └── from_test
│       ├── execute
│       │   ├── data
│       │   │   └── repro
│       │   │       ├── bkr
│       │   │       │   ├── clbuff
│       │   │       │   ├── cleanup.sh
│       │   │       │   ├── journal_colored.txt
│       │   │       │   ├── journal.meta
│       │   │       │   ├── journal.txt
│       │   │       │   ├── journal.xml
│       │   │       │   ├── metadata.yaml
│       │   │       │   ├── output.txt
│       │   │       │   ├── PersistentData
│       │   │       │   ├── submitted
│       │   │       │   │   └── to_submit
│       │   │       │   ├── TestResults
│       │   │       │   └── touched_in_bkr_test
│       │   │       └── shell
│       │   │           ├── from_test
│       │   │           ├── metadata.yaml
│       │   │           └── output.txt
│       │   ├── default
│       │   │   └── reboot_template
│       │   ├── results.yaml
│       │   ├── step.yaml
│       │   └── tmt-file-submit



```

**Comment by lukaszachy** [comment]
Example when TMT_TEST_DATA points to 'data' subdir - and is same location where rlSubmit stores files.. So one can learn -- all my files are in 'data' subdir. No name colisions
```
├── repro
│   └── plan
│       ├── execute
│       │   ├── data
│       │   │   └── repro
│       │   │       ├── bkr
│       │   │       │   ├── clbuff
│       │   │       │   ├── cleanup.sh
│       │   │       │   ├── data
│       │   │       │   │   ├── to_submit
│       │   │       │   │   └── touched_in_bkr_test
│       │   │       │   ├── journal_colored.txt
│       │   │       │   ├── journal.meta
│       │   │       │   ├── journal.txt
│       │   │       │   ├── journal.xml
│       │   │       │   ├── metadata.yaml
│       │   │       │   ├── output.txt
│       │   │       │   ├── PersistentData
│       │   │       │   └── TestResults
│       │   │       └── shell
│       │   │           ├── data
│       │   │           │   └── from_test
│       │   │           ├── metadata.yaml
│       │   │           └── output.txt
```

**Comment by psss** [comment]
Sounds good, I'm fine with that. Let's try with a dedicated `data` directory.

**Comment by psss** [comment]
Tests are green, @lukaszachy are we ready to squash?

**Review by lukaszachy — APPROVED** [review]

**Comment by lukaszachy** [comment]
LGTM - Worked very well

**Comment by psss** [comment]
Great, thanks for the review! Squashed.

**Pull request merged**
