### PR TITLE
Add podman provisioner

### PR DESCRIPTION
**Pull request by thrix**
This patch adds podman provisioner which for now also provides 'how: container'.

Along comes a test for it:

    tmt run plan --name container

Also add a new subpackage tmt-container to install this provisioner
dependencies.

TODO:
- [ ] discuss and fix container cleanup, now all containers stay up and running ....
- [ ] add test for shell executor

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

### CODE REVIEW

**Comment by thrix** [comment]
@psss any idea why we do not build tmt-container, is there anything else missing  from the spec??

**Comment by psss** [comment]
> @psss any idea why we do not build tmt-container, is there anything else missing from the spec??

Hm, probably `no file, no package`. I've included at least license as for the `tmt-all`. Now it builts correctly.

**Comment by psss** [comment]
Thanks much for implementing this, @thrix! Merged to master :-)

**Comment by pvalena** [comment]
> Hm, probably `no file, no package`. I've included at least license as for the `tmt-all`. Now it builts correctly.

Yes, that's correct. Why doesn't it have any container-specific files? (Why do we actually need it?)

**Comment by pvalena** [comment]
@psss  Also please vary of mixing various versions of your sub-packages (by default the subpackage does not depend on specific version of a "main" package it's built with).

**Pull request merged**
