### PR TITLE
thread processing of executed commands inside tmt

### PR DESCRIPTION
**Pull request by jscotka**
new version of threading of process based on packit code

It replaces original PR: https://github.com/psss/tmt/pull/763

### CODE REVIEW

**Comment by lukaszachy** [comment]
Implementation looks good but I'd prefer to try this (at least locally) for more time.

**Comment by psss** [comment]
@thrix has tested this change in Testing Farm:

 * tmt test against an FMF PR
 * installability
 * rpminspect

Seems to be working fine. Details in TFT-811.

**Review by lukaszachy — APPROVED** [review]
Need to squash commits but feature-wise LGTM

**Comment by lukaszachy** [comment]
Thank you very much @jscotka for this PR.

**Pull request merged**
