### PR TITLE
Avoid multiple calls for Node.fmf_id property code, it is constant

### PR DESCRIPTION
**Pull request by jscotka**
Should help other PR's to spent time to call this property code and cache the result

### CODE REVIEW

**Review by lukaszachy — APPROVED** [review]
Very nice. Python rocks.

**Comment by lukaszachy** [comment]
Lets' try newly proposed process ;) 
Could you change the commit message to conform  https://tmt.readthedocs.io/en/latest/contribute.html#commits please?
E.g. `Cache fmf_id property`

**Comment by thrix** [comment]
pls rebase on top of master branch, all the errors are caused by some change @psss did last days

**Review by psss — APPROVED** [review]
Nice, this looks like a very elegant way to solve this! :-)

**Comment by jscotka** [comment]
> pls rebase on top of master branch, all the errors are caused by some change @psss did last days

done I hope

**Pull request merged**
