### PR TITLE
Feature/load env from url

### LINKED ISSUE #840: Feature environment-file-url. Load env vars from a file located at url
Follow up from #795 . I have a problem of introducing environment file which contains  secrets for the case when tests are executed in the remote environment. For local execution environment-file is fine. 

In our case when running test on testing farm or via packit our main plan would look like this:
```yaml
execute:
    how: tmt
discover:
    how: fmf
prepare:
    - name: main preparation step
      how: ansible
      playbook: tests/ansible_collections/main.yml
environment-file:
  - .env
adjust:
  - environment-file-:
    - .env
    when: distro != ""
  - environment-file-url:
      - https://some-repo-with-secrets/secrets.yaml
      - https://some-repo-with-secrets/.env
    when: distro != ""
```

By using this `when: distro != ""` I am trying to use what we have in the packet CI. Packit specifies distro context, so if distro is not empty, then I know that the tmt run executed in the CI, so I need env vars from url

### PR DESCRIPTION
**Pull request by ZhukovGreen**
resolves #840 
Follow-up from #795 and **based on top of it**

Allows to specify the env vars at URL

Usage example:
```yaml
/with_fmf_parameter:
    summary: This is a plan with vars provided by fmf
    environment-file-url:
      - https://some-url-to-secrets/.env
      - https://some-url-to-secrets/.env.yaml
```

from cli:
```bash
tmt run --environment-file-url https://some-url-to-secrets/.env
```

### CODE REVIEW

**Comment by pvalena** [comment]
Question1: Is this intended to overwrite current ENV? Like f.e. if it redefines `PATH`, or .

Question2: Is the host ENV affected as well (during `discover` f.e.)? I'm no expert, but I suspect it can have some security implications.

**Comment by ZhukovGreen** [comment]
@pvalena 
> Question1: Is this intended to overwrite current ENV? Like f.e. if it redefines PATH, or .

not. The test https://github.com/psss/tmt/pull/841/files#diff-019717de60a805cd16ce2a5e22b9000840e9949566a3e09691cbb9e512a7dc9fR73 covers this case

> Question2: Is the host ENV affected as well (during discover f.e.)? I'm no expert, but I suspect it can have some security implications.

Env vars loaded to the main python process where the tmt runs. It is not updating the host environment. Moreover the plan related env vars are cleaned at the end of each plan

**Comment by pvalena** [comment]
> @pvalena
> 
> > Question1: Is this intended to overwrite current ENV? Like f.e. if it redefines PATH, or .
> 
> not. The test https://github.com/psss/tmt/pull/841/files#diff-019717de60a805cd16ce2a5e22b9000840e9949566a3e09691cbb9e512a7dc9fR73 covers this case

Great!
Sorry, I couldn't tell from the test case.
 
> Env vars loaded to the main python process where the tmt runs. It is not updating the host environment. Moreover the plan related env vars are cleaned at the end of each plan

Right, which runs on the host. This should be hopefully mostly covered by my first question. _Please just note that there are ENV variables which are considered dangerous:_
https://tldp.org/HOWTO/Secure-Programs-HOWTO/environment-variables.html
 - I can't however tell if that can be somehow used to escape/gain control of the python process; or some shell created by it.

**Comment by lukaszachy** [comment]
Do we need another option? Why not just allowing URI in `--environment-file` (http, https, file and path (absolute and relative)

**Comment by psss** [comment]
> Do we need another option? Why not just allowing URI in `--environment-file` (http, https, file and path (absolute and relative)

Agreed, plus one for this approach.

**Comment by ZhukovGreen** [comment]
OK, I'll solve it under the same parameter

**Comment by ZhukovGreen** [comment]
closing this MR in favour of #795

**Pull request closed without merging**
