### PR TITLE
Fix login not working for cloud images

### LINKED ISSUE #601: prepare step fails with cryptic error if ansible playbook is run against a vm with root auth disabled
Steps to reproduce:
1. Vm with root auth disabled (like vanilla cloud rhel7.9 image, discovered with latest openstack rhel7.9 image)
2. `tmt run -a provision  -h connect -g YOUR_VM_IP_HERE `

This will fail with cryptic 
```
protocol version mismatch -- is your shell clean?
 
Failed to run command 'rsync -Rrz --links --safe-links --delete -e "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/ivasilev/.ssh/id_rsa" --safe-links /var/tmp/tmt/run-021/plans/integration root@10.0.79.174:/'.
```

If step 2 is run with user specified like `tmt run -a provision  -h connect -g 10.0.79.174 --user cloud-user` or the rsync command is executed manually as 
```
rsync -Rrz --links --safe-links --delete -e "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/ivasilev/.ssh/id_rsa" --safe-links /var/tmp/tmt/run-021/plans/integration cloud-user@10.0.79.174:/ 
```
 the issue is not there.

### PR DESCRIPTION
**Pull request by thrix**
Handle better problems encountered when logging in to the instance.

In case cloud image standard message, inform the user about it:

```
Login to server failed. Please login as the user 'cloud-user' rather then the user 'root'.
```

The second part of the sentence is directly taken from the ssh reply ...

In case `authorized_keys` forces a weird command, which breaking login,
report it to the user as:

```
Failed to push workdir to the machine. This usually means login as 'root' to the test machine does not work.
```

Resolves #601

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

### CODE REVIEW

**Review by psss — APPROVED** [review]
Thanks for improving this. Added a few minor adjustments. I think it's good to have the full error available as well:

```
    prepare
        workdir: /var/tmp/tmt/run-210/plans/default/prepare
        fail: Failed to push workdir to the guest. This usually means login as 'root' to the test machine does not work.

stderr (4/4 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Warning: Permanently added '[127.0.0.1]:10039' (ECDSA) to the list of known hosts.
Permission denied, please try again.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]

Failed to run command 'rsync -Rrz --links --safe-links --delete -e "sshpass -phm ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 10039" /var/tmp/tmt/run-210/plans/default root@127.0.0.1:/'.
```

Does it look good to you?

**Review by lukaszachy — APPROVED** [review]

**Comment by thrix** [comment]
> Thanks for improving this. Added a few minor adjustments. I think it's good to have the full error available as well:
> 
> ```
>     prepare
>         workdir: /var/tmp/tmt/run-210/plans/default/prepare
>         fail: Failed to push workdir to the guest. This usually means login as 'root' to the test machine does not work.
> 
> stderr (4/4 lines)
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Warning: Permanently added '[127.0.0.1]:10039' (ECDSA) to the list of known hosts.
> Permission denied, please try again.
> rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]
> 
> Failed to run command 'rsync -Rrz --links --safe-links --delete -e "sshpass -phm ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 10039" /var/tmp/tmt/run-210/plans/default root@127.0.0.1:/'.
> ```
> 
> Does it look good to you?

Well, I am not sure :) Users will miss it as before ... the nice failure is a bit hidden to me

**Comment by thrix** [comment]
9

> > Thanks for improving this. Added a few minor adjustments. I think it's good to have the full error available as well:
> > ```
> >     prepare
> >         workdir: /var/tmp/tmt/run-210/plans/default/prepare
> >         fail: Failed to push workdir to the guest. This usually means login as 'root' to the test machine does not work.
> > 
> > stderr (4/4 lines)
> > ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > Warning: Permanently added '[127.0.0.1]:10039' (ECDSA) to the list of known hosts.
> > Permission denied, please try again.
> > rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> > rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]
> > 
> > Failed to run command 'rsync -Rrz --links --safe-links --delete -e "sshpass -phm ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 10039" /var/tmp/tmt/run-210/plans/default root@127.0.0.1:/'.
> > ```
> > 
> > 
> > Does it look good to you?
> 
> Well, I am not sure :) Users will miss it as before ... the nice failure is a bit hidden to me

I am not sure, that rsync error is very misleading, not sure why to show it

**Comment by psss** [comment]
> I am not sure, that rsync error is very misleading, not sure why to show it

I think it is essential for investigating issues. If you end up only with "This usually means..." but are unable to find out what the real problem was in that particular case, it does not help. Combining both seems to me as the best solution.

**Comment by thrix** [comment]
@psss mmkay, let's try it, better then before anyway, so you have my :blessing:

**Comment by psss** [comment]
Thanks!

**Pull request merged**
