### PR TITLE
Add support for reboot in a reused provision

### PR DESCRIPTION
**Pull request by FrNecas**
Previously, the reboot implementations would be only synced the first
time the plan was run. The token would be however updated in the second
run and hence reboot would not be correctly detected. Backup the
previous {rstrnt, rhts, tmt}-reboot implementations and then override
them always with the new one.

If you run the test locally right now, it may fail. This will be resolved by https://github.com/psss/tmt/pull/892 (or you can just add a sleep to `reconnect()`)

### CODE REVIEW

**Review by psss — APPROVED** [review]
Thanks for the improvement, looks good. I just moved debug messages to level 2.

**Comment by FrNecas** [comment]
Thanks for the review and also rebase with the new changes to reconnect and exitfirst :)

**Comment by psss** [comment]
Tests passed, the only failure is the known `Could not resolve host` issue. Merging.

**Pull request merged**
