### PR TITLE
Extend .gitignore with a few more common patterns

### PR DESCRIPTION
**Pull request by psss**
Let's gather more common stuff in this pull request and merge at once.

### CODE REVIEW

**Review by hegerj — APPROVED** [review]
LGTM

**Review by lukaszachy — APPROVED** [review]

**Comment by psss** [comment]
@FrNecas, I guess you had on mind a couple of other sections to be added, right?

**Review by FrNecas — APPROVED** [review]
@psss Yes, I added a few more things specific to Python and categorized the existing ignores so that it is consistent with Vim. Temporary python stuff should be now handled a bit better, I also added common names for virtual environments (such as env/venv), as some may prefer having a virtualenv in their repo rather than using mkvirtualenv.

**Comment by psss** [comment]
Thanks for the enhancements, @FrNecas! Looks great to me.

**Pull request merged**
