### PR TITLE
vagrant: Add default config for libvirt to use QEMU session

### PR DESCRIPTION
**Pull request by pvalena**
Also fix workdir to use plan one.
And also Fix inheritance.

### CODE REVIEW

**Comment by psss** [comment]
I cherry-picked and merged 5b208b5. But the f28dd11 part broke provison for me:

    stderr:  There are errors in the configuration of this
    machine. Please fix the following errors and try again:

    Libvirt Provider:
    * The following settings shouldn't exist: qemu_use_session

Could you have a look at it?

**Comment by pvalena** [comment]
Fixup comming right up.

**Comment by pvalena** [comment]
Fixed + Refactored. Tests pass.

`tmt run provision` still fails:
```

  File "/home/lpcs/lpcsf-new/test/tmt/tmt/steps/discover/__init__.py", line 39, in wake
    self.steps.append(DiscoverShell(data, step=self))
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/steps/discover/shell.py", line 14, in __init__
    super(DiscoverShell, self).__init__(step=step, name=data['name'])
TypeError: __init__() missing 1 required positional argument: 'data'
```

I've also tried:
```
tmt run tests '*'
/var/tmp/tmt/run-040

/plans/basic
    discover
        how: fmf
        repository: https://github.com/psss/tmt
        revision: devel
Traceback (most recent call last):
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/bin/tmt", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/lpcs/lpcsf-new/test/tmt/bin/tmt", line 11, in <module>
    tmt.cli.main()
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/core.py", line 1101, in _process_result
    value = ctx.invoke(self.result_callback, value,
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/cli.py", line 269, in finito
    context.obj.run.go()
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/base.py", line 533, in go
    plan.go()
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/base.py", line 310, in go
    step.go()
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/steps/discover/__init__.py", line 59, in go
    self.save()
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/steps/discover/__init__.py", line 26, in save
    tests = dict([test.export(format_='execute') for test in self.tests()])
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/steps/discover/__init__.py", line 26, in <listcomp>
    tests = dict([test.export(format_='execute') for test in self.tests()])
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/steps/discover/__init__.py", line 65, in tests
    for test in step.tests():
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/steps/discover/fmf.py", line 86, in tests
    tests = [
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/steps/discover/fmf.py", line 86, in <listcomp>
    tests = [
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/fmf/base.py", line 362, in prune
    [re.search(name, node.name) for name in names]):
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/fmf/base.py", line 362, in <listcomp>
    [re.search(name, node.name) for name in names]):
  File "/usr/lib64/python3.8/re.py", line 199, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib64/python3.8/re.py", line 302, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib64/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib64/python3.8/sre_parse.py", line 668, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
```

**Comment by pvalena** [comment]
And for some reason it does not regexp the plans / tests. How does it work?
```
tmt run tests 'basic'
/var/tmp/tmt/run-041

/plans/basic
    discover
        how: fmf
        repository: https://github.com/psss/tmt
        revision: devel
        tests: 0 tests selected
    provision
        provisioning localhost
        saving localhost
    prepare
    execute
    report
    finish

/plans/helps
Traceback (most recent call last):
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/bin/tmt", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/lpcs/lpcsf-new/test/tmt/bin/tmt", line 11, in <module>
    tmt.cli.main()
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/core.py", line 1101, in _process_result
    value = ctx.invoke(self.result_callback, value,
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lpcs/lpcsf-new/test/tmt/project_venv/lib64/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/cli.py", line 269, in finito
    context.obj.run.go()
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/base.py", line 533, in go
    plan.go()
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/base.py", line 307, in go
    step.wake()
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/steps/discover/__init__.py", line 39, in wake
    self.steps.append(DiscoverShell(data, step=self))
  File "/home/lpcs/lpcsf-new/test/tmt/tmt/steps/discover/shell.py", line 14, in __init__
    super(DiscoverShell, self).__init__(step=step, name=data['name'])
TypeError: __init__() missing 1 required positional argument: 'data'
```

**Comment by pvalena** [comment]
Success, feel free to merge:
```
$ tmt run plan '/plans/smoke'
/var/tmp/tmt/run-051

/plans/smoke
    discover
        how: fmf
        directory: /home/lpcs/lpcsf-new/test/tmt
        tests: 2 tests selected
    provision
         Provisioning vagrant, this is the Vagrantfile:
         Vagrantfile = \
                       Vagrant.configure("2") do |config|
                         config.vm.box = "centos/7"
                         config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: true
                         config.vm.synced_folder "/var/tmp/tmt/run-051/plans/smoke", "/var/tmp/tmt/run-051/plans/smoke", type: "rsync"
                         config.vm.provider 'libvirt' do |libvirt| libvirt.qemu_use_session = true ; end
                       end


         command = vagrantup
         stdout = \
                  Bringing machine 'default' up with 'libvirt' provider...
                  ==> default: Checking if box 'centos/7' version '1905.1' is up to date...
                  ==> default: Creating image (snapshot of base box volume).
                  ==> default: Creating domain with the following settings...
                  ==> default:  -- Name:              hsoIbHnQZQfjHHoJ_default
                  ==> default:  -- Domain type:       kvm
                  ==> default:  -- Cpus:              1
                  ==> default:  -- Feature:           acpi
                  ==> default:  -- Feature:           apic
                  ==> default:  -- Feature:           pae
                  ==> default:  -- Memory:            512M
                  ==> default:  -- Management MAC:
                  ==> default:  -- Loader:
                  ==> default:  -- Nvram:
                  ==> default:  -- Base box:          centos/7
                  ==> default:  -- Storage pool:      default
                  ==> default:  -- Image:             /home/lpcs/.local/share/libvirt/images/hsoIbHnQZQfjHHoJ_default.img (41G)
                  ==> default:  -- Volume Cache:      default
                  ==> default:  -- Kernel:
                  ==> default:  -- Initrd:
                  ==> default:  -- Graphics Type:     vnc
                  ==> default:  -- Graphics Port:     -1
                  ==> default:  -- Graphics IP:       127.0.0.1
                  ==> default:  -- Graphics Password: Not defined
                  ==> default:  -- Video Type:        cirrus
                  ==> default:  -- Video VRAM:        9216
                  ==> default:  -- Sound Type:
                  ==> default:  -- Keymap:            en-us
                  ==> default:  -- TPM Path:
                  ==> default:  -- INPUT:             type=mouse, bus=ps2
                  ==> default: Creating shared folders metadata...
                  ==> default: Starting domain.
                  ==> default: Waiting for domain to get an IP address...
                  ==> default: Waiting for SSH to become available...
                      default:
                      default: Vagrant insecure key detected. Vagrant will automatically replace
                      default: this with a newly generated keypair for better security.
                      default:
                      default: Inserting generated public key within guest...
                      default: Removing insecure key from the guest if it's present...
                      default: Key inserted! Disconnecting and reconnecting using new SSH key...
                  ==> default: Configuring and enabling network interfaces...
                      default: SSH address: 192.168.122.111:22
                      default: SSH username: vagrant
                      default: SSH auth method: private key
                  ==> default: Rsyncing folder: /var/tmp/tmt/run-051/plans/smoke/ => /var/tmp/tmt/run-051/plans/smoke
         stderr = \
                  /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/config.rb:625: warning: Insecure world writable dir /home/lpcs/lpcsf-new/test in PATH, mode 040777
         returncode = 0
    prepare
    execute
    report
    finish
```

However I did not try older Ruby version.

**Comment by psss** [comment]
Great, works for me as well. Merging.

**Pull request merged**
