### PR TITLE
Release tmt-1.8.0

### PR DESCRIPTION
**Pull request by lukaszachy**
Following https://tmt.readthedocs.io/en/latest/contribute.html#release

Follow the steps below to create a new major or minor release:

- [x] Run the full test coverage using tmt -c how=full run
- [x] Use git log --oneline x.y-1.. to generate the changelog
- [x] Add a Release tmt-x.y.0 commit with the specfile update
- [x] Create a pull request with the commit, ensure tests pass

Release a new package to Fedora and EPEL repositories:

- [x] Move the fedora branch to point to the new release
- [x] Create a source rpm using the make srpm command
- [x] Enable Fedora kerberos kinit nick@FEDORAPROJECT.ORG
- [x] Change to the fedora rpms git or fedpkg clone tmt
- [x] Check out the rawhide branch git checkout rawhide
- [x] Import the srpm using fedpkg import /path/to/the/srpm
- [x] Restore any files removed by fedpkg if necessary
- [x] Ensure the proposed changes are ok and commit them
- [x] Create a pull request against rawhide from your fork
- [x] After tests pass, merge the pull request to rawhide
- [x] Build the package for rawhide fedkpkg build --nowait
- [x] Build package for all active releases git checkout f33 && git merge rawhide && git push && fedpkg build --nowait
- [x] Create a bodhi update for each release git checkout f33 && fedpkg update --type enhancement --notes 'Update title'

Finally, if everything went well:

- [ ] Merge the original release pull request on github
- [ ] Tag the commit with x.y.0, push tags git push --tags
- [ ] Create a new github release based on the tag above
- [ ] Close the corresponding release milestone
If the automation triggered by publishing the new github release was not successful, publish the fresh code to the pypi repository manually:

make wheel
make upload
- [ ] Once the copr build is completed, move the quay branch to point to the release commit as well to build fresh container images.

### CODE REVIEW

**Comment by lukaszachy** [comment]
Squeezing one more commit

**Review by psss — APPROVED** [review]
Everything looks great!

**Comment by lukaszachy** [comment]
Pypi updated automatically: https://pypi.org/project/tmt/1.8.0/

**Comment by lukaszachy** [comment]
Copr build finished:  https://copr.fedorainfracloud.org/coprs/psss/tmt/build/2868714/

**Pull request merged**
