### PR TITLE
Guest.details() now uses /etc/os-release

### PR DESCRIPTION
**Pull request by navtom**

### CODE REVIEW

**Comment by pvalena** [comment]
LGTM.

**Comment by psss** [comment]
This should fix #310.

**Comment by psss** [comment]
@navtom, thanks for the pull request. I've tested with fedora, rhel, centos and ubuntu. Works fine, except for RHEL6 / CentOS 6. It seems there are only the following release files available:

    /etc/centos-release
    /etc/redhat-release -> centos-release
    /etc/system-release -> centos-release
    /etc/system-release-cpe

Seems we still have to add `/etc/redhat-release` as a (last) fallback. @navtom, could you please squash the commits so that there is only one? Also, it seems your git email address is not properly configured:

    > git log | head -2
    commit 619c78f2827377d1755ae131bd944171483bcdf3
    Author: root <root@DESKTOP-C4H30DU.localdomain>

Thanks.

**Comment by navtom** [comment]
Done. OS info is extracted from os-release, lsb-release or redhat-release in this order.

**Comment by psss** [comment]
Thanks for the update, @navtom. Looks good now and works across all distros. Added just a couple of minor adjustments.

**Comment by psss** [comment]
Rebased on the latest master and merged.

**Pull request merged**
