### PR TITLE
'sync-back' and simple 'preparator' prototype for VagrantProvision

### PR DESCRIPTION
**Pull request by pvalena**
**Important: I've not tested 'sync-back', nor preparator (but it _should_ work). And I'm thinking about better solution for both...**
The prepare step Itself will be in another PR.
Feel free to merge it if it works for you, we can enhance it later on.
_ _ _ _

Implement 'sync-back' and simple 'preparator' prototype.

Additionaly:
  * handle images properly
  * better debug/info: pass it (to super) every time
  * move init() to go()
  * abstract add_config_block
  * resume correctly with existing Vagrantfile
  * Better Vagrant 'config' handling

### CODE REVIEW

**Comment by pvalena** [comment]
_FTR:_ What is needed, additionaly to this PR:

 - https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1058 for compatibility with system `vagrant-libvirt` on Fedora (dependency on `fog-core`)
 - decide to use either `vagrant-scp` or `vagrant-rsync-back` with `git-ignore`
 - decide whether to create an `VagrantOrchestrator` _(not sure about the name)_ and inherit general methods from it (untrivial implementation, even now) for `VagrantProvider` and `VagrantPreparer`. _(It would make sense to me, but we need some consensus.)_

**Comment by psss** [comment]
Looks good for now. Merged. I tried to enable sync-back, but failed with this error:
  
    Run command '('vagrant', 'plugin', 'install', 'vagrant-rsync-back')'.
    out: Installing the 'vagrant-rsync-back' plugin. This can take a few minutes...
    err: Vagrant failed to properly resolve required dependencies. These
    err: errors can commonly be caused by misconfigured plugin installations
    err: or transient network issues. The reported error is:
    err
    err: conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 2.1.2)
    err:   Activated fog-core-2.1.2
    err:   which does not match conflicting dependency (~> 1.43.0)
    err
    err:   Conflicting dependency chains:
    err:     fog-core (= 2.1.2), 2.1.2 activated
    err
    err:   versus:
    err:     vagrant-libvirt (> 0), 0.0.41 activated, depends on
    err:     fog-core (~> 1.43.0)

That seems to be related to the `fog-core` issue mentioned above.

**Comment by pvalena** [comment]
Yes, that's the linked issue; for quick workaround do:
```
$ sudo dnf remove vagrant-libvirt -y && vagrant plugin install vagrant-ilbvirt
```

Additionally, I'll  package vagrant-rsync-back into my COPR, possibly into Fedora later on.

**Comment by pvalena** [comment]
I personally run the following:

```
➜  for p in ruby-devel rubygem-{formatador,excon,builder,ruby-libvirt} ; do dnf -q install -yb "$p" ; rpm -q "$p" ; done
ruby-devel-2.6.5-124.fc32.x86_64
rubygem-formatador-0.2.5-8.fc32.noarch
rubygem-excon-0.65.0-1.fc32.noarch
rubygem-builder-3.2.3-7.fc31.noarch
rubygem-ruby-libvirt-0.7.1-6.fc31.x86_64
➜  vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching fog-core-1.43.0.gem
Fetching fog-xml-0.1.3.gem
Fetching fog-json-1.2.0.gem
Fetching fog-libvirt-0.7.0.gem
Fetching vagrant-libvirt-0.0.45.gem
Parsing documentation for fog-core-1.43.0
Installing ri documentation for fog-core-1.43.0
Parsing documentation for fog-xml-0.1.3
Installing ri documentation for fog-xml-0.1.3
Parsing documentation for fog-json-1.2.0
Installing ri documentation for fog-json-1.2.0
Parsing documentation for fog-libvirt-0.7.0
Installing ri documentation for fog-libvirt-0.7.0
Parsing documentation for vagrant-libvirt-0.0.45
Installing ri documentation for vagrant-libvirt-0.0.45
Done installing documentation for fog-core, fog-xml, fog-json, fog-libvirt, vagrant-libvirt after 1 seconds
Installed the plugin 'vagrant-libvirt (0.0.45)'!
```

**Comment by psss** [comment]
Uninstalling the `rubygem-fog-core` help. Documented in 6a0dd20.

**Comment by pvalena** [comment]
Yes, basically. fog* packages are the real conflict itself, as the error message states. But it is a temporary problem, as it will be solved upstream+downstream as I mentined earlier (and I've created a helpful error message in #30).
Uninstalling all vagrant-* plugins should be sufficient, as I can't think of any other reason you'd have fog-* gems installed (and the resolver probably won't use them if you don't have the plugin load them; Ruby itself supports multiple versions of gems installed).

**Pull request merged**
