### PR TITLE
Check if connection is running in Vagrant Provision

### PR DESCRIPTION
**Pull request by pvalena**
also recover from failed Prepare,
speedup VF creation and try destroy multiple times on fail.

### CODE REVIEW

**Comment by pvalena** [comment]
During testing I've found there are some bugs :) please do not merge yet.

**Comment by pvalena** [comment]
Hmm how did this history thing happen?

**Comment by pvalena** [comment]
Ah, you've made master non-fast-forwardable :/

**Comment by pvalena** [comment]
Should be all good to go now.

**Comment by psss** [comment]
> Ah, you've made master non-fast-forwardable :/

That's weird. I don't remember any force-push commit to master.

**Pull request merged**
