### PR TITLE
Export manual attribute

### PR DESCRIPTION
**Pull request by hegerj**

### CODE REVIEW

**Comment by hegerj** [comment]
Fixes #430

**Review by psss — APPROVED** [review]
Looks good, I just propose to use consistent naming/terminology for the attribute name.

**Comment by psss** [comment]
Test submission failed with:

     Failed to submit tests: METHOD NOT ALLOWED

@thrix, @lachmanfrantisek have you seen already anything like this?

**Comment by lachmanfrantisek** [comment]
> @thrix, @lachmanfrantisek have you seen already anything like this?

I [started seeing](https://github.com/packit/hello-world/pull/109) that yesterday on both stg on prod so it looks like some problem on testing-farm side. Can you please take a look, @thrix?

**Comment by thrix** [comment]
Nope, will look at it right away

**Comment by thrix** [comment]
very disturbing, hash of the image changed in quay

**Comment by thrix** [comment]
or they deleted some old image :(

**Comment by lachmanfrantisek** [comment]
Thanks @thrix !

**Comment by thrix** [comment]
should look better soon

**Comment by thrix** [comment]
oh yes

**Comment by psss** [comment]
Thanks for the fix, @thrix.

**Pull request merged**
