### PR TITLE
Add COPR build for master

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
I remember that you were interested in the COPR builds for new commits to `master` branch.

This will build in your COPR project (`psss/tmt`). (Packit should ask you for `builder` permission.)
If you don't set the `owner`+`project`, we will create `packit/psss-tmt-master` for you.

### CODE REVIEW

**Comment by psss** [comment]
Nice, thanks for the improvement! For now the `packit/psss-tmt-master` repo would be ideal. So I can keep the config as it is now?

**Comment by lachmanfrantisek** [comment]
You are welcome. We have that for some time already but we probably need to share this more..;)

> For now the packit/psss-tmt-master repo would be ideal.

I see you fixed that by yourself, thanks:
https://github.com/psss/tmt/commit/4338162343e9d47d69c8490316967ca922d96812

**Comment by psss** [comment]
@lachmanfrantisek, just noticed after switch to the main copr repo: Packit needs the "admin" permission to the repo?

**Comment by lachmanfrantisek** [comment]
> @lachmanfrantisek, just noticed after switch to the main copr repo: Packit needs the "admin" permission to the repo?

Only when we need to change settings -- e.g. chroots.

For PRs, you should get a comment with the required changes and you can choose if you do the change manually or give us the admin permissions. For branch builds, we have only commit status for now.

**Comment by psss** [comment]
I see, thanks for clarification.

**Pull request merged**
