### PR TITLE
Show link to log.txt in report html

### PR DESCRIPTION
**Pull request by lukaszachy**
Handy when checking what/where was installed

### CODE REVIEW

**Review by psss — APPROVED** [review]
Nice & handy. What about placing the log at the bottom with a simple heading and style?

**Comment by lukaszachy** [comment]
Footer is a good place but how to make the separation cleaner?
Screenshot_2021-04-27 Test results of plans example

**Comment by lukaszachy** [comment]
@psss I've enlarged margin and put footer into its own class.

**Comment by psss** [comment]
Yeah, good idea. Simplified the `margin` definition and squashed.

**Pull request merged**
