### PR TITLE
Apply filters after applying defaults and conversions

### PR DESCRIPTION
**Pull request by FrNecas**
Tmt makes automatic conversions and applies defaults to tests, plans and
stories, however, fmf has no clue about such actions. Previously,
filters and conditions were applied on the raw fmf data (with no
conversions taken into account) which could result in weird errors
(e.g. Test.tag could be set to None when filtering).

Change this behaviour so that filters and conditions are applied after
the Tree has been processed by tmt, in other words once Test/Story/Plan
objects have been created.

Resolves: #469
Resolves: #450 

Following the example in the issue produces the following expected result:
```
$ tmt tests ls --condition '"nonex" not in tag'
/nulltag-test
$ tmt tests ls --condition '"nonex" in tag'
$ tmt tests ls --condition 'tag is None'
$ tmt tests ls --condition 'not tag'
/nulltag-test
```

### CODE REVIEW

**Comment by psss** [comment]
Thanks for fixing this, @FrNecas. The essential part looks good. I've slightly improved the code to prevent unnecessary duplication and extended tests a bit. Before merging we should still cover the following:

1. Handle exceptions raised in `fmf.utils.filter()` (e.g. missing dimension in data dict)
2. Handle exceptions raised in `fmf.utils.evaluate()` (e.g. any invalid python code)
3. Decide what do we do with custom L1 attributes (anything which is not part of the spec)

Regarding the last one: Users can define and use arbitrary metadata for their tests and then use them for filtering. We should probably support these as well. What do you think?

**Comment by FrNecas** [comment]
Rebased to master, added exception handling, boolean values with lowercase are now supported on tmt side and custom attributes are supported as well (I moved `_metadata` attribute to `Node` to share the logic for all the node types)

**Review by psss — APPROVED** [review]
Looks good and works as expected. Please have a look at my last commit with a couple adjustments. I fixed `make docs` which was broken by `Story.export()` missing support for `dict`, updated the spec a bit and changed the behaviour when conditions/filters specify attributes which are not defined (the problem revealed by `/tests/plan/select` searching across plans). Not completely sure about this one, but this is how it's implemented in `fmf`. Or shall we really give up when filter contains undefined attribute? @FrNecas, @lukaszachy, what do you think?

**Comment by thrix** [comment]
Hmm, seems CentOS8 error is from `tmt` ...

**Comment by lukaszachy** [comment]
IMHO it is correct to treat missing attributes as false (as opposed to filter error). 
E.g. As a user I want to find all tests which are using specific unofficial attribute (e.g. extra-hardware)

**Comment by psss** [comment]
Good, let's merge then. We can adjust/polish this later if needed.

**Pull request merged**
