### PR TITLE
Ansible plugin for Finish step

### LINKED ISSUE #919: [feature request] Possibility to use ansible playbooks in finish step
Complex setup cases (where ansible can be used in prepare step) sometimes require a non-trivial teardown, but unfortunately now only `how: bash` is allowed in finish step.

```
/tests/plans/integration/postupgrade/e2e/7to8sap
Unsupported finish method 'ansible' in the '/tests/plans/integration/postupgrade/e2e/7to8sap' plan.
```

### PR DESCRIPTION
**Pull request by lukaszachy**
Resolve #919

Copy & paste from prepare/ansible.py with necessary modifications

### CODE REVIEW

**Comment by lukaszachy** [comment]
@FrNecas another attempt. Works for me (tm) :)

**Comment by FrNecas** [comment]
@lukaszachy looks a lot better now without the copy paste, thanks :) Though you can see even LGTM bot shouting, I think the problem is name resolution. Because right now, you have for example `go` method in both of the parent classes. I've just experimented with the following code:
```python
class A:
    def foo(self):
        print("A")

class B:
    def foo(self):
        print("B")

class C(B, A):
    pass

c = C()
c.foo()
```
and python seems to take the first inherited class which works in this case. I am just not sure if this is guaranteed by Python so it may be better to explicitly specify where we are inhering from using `super`:

```python
def go():
    super(PrepareAnsible, self).go()
```

**Comment by lukaszachy** [comment]
Lets see what LGTM says now.
IMHO we don't need to redefine 'go()' - it is defined only in PrepareAnsible (and their common ancestor Plugin)

**Review by FrNecas — APPROVED** [review]
Sorry for the delay on my side. You are right that the method resolution works now correctly, though I was a bit surprised by it (the inheritance topography is a diamond which may cause problems when not being careful). Just for reference, the MRO is:

```
>>> FinishAnsible.mro()
[<class 'tmt.steps.finish.ansible.FinishAnsible'>, <class 'tmt.steps.finish.FinishPlugin'>,
<class 'tmt.steps.prepare.ansible.PrepareAnsible'>, <class 'tmt.steps.prepare.PreparePlugin'>, <class 'tmt.steps.Plugin'>, <class 'tmt.utils.Common'>, <class 'object'>]
```
Which means that it's taken from `PrepareAnsible` before going on to the general plugins which have the abstract unimplemented methods. And AFAIK everything should be taken from `PrepareAnsible` unless overriden, so that should be fine.

**Pull request merged**
