### PR TITLE
Fix missing overview on the readthedocs.org site

### PR DESCRIPTION
**Pull request by psss**
The `overview.rst` cannot be generated by Makefile.
Include reference anchors in all important pages.
Add a new plan to cover documentation building.
Extend `/tests/core/docs` to check for man page warnings.

### CODE REVIEW

**Comment by hegerj** [comment]
I am a bit confused here, why are you removing `overview.rst`? And what's the difference between `overview.rst` and `README.rst`?

**Comment by psss** [comment]
This pull request is returning the symlink from `overview.rst` to `README.rst` as building the documentation on the readthedocs server cannot include using `make`.

**Comment by psss** [comment]
Would be nice to get this merged soon as the [overview](https://tmt.readthedocs.io/en/latest/overview.html) page is gone...

**Review by thrix — APPROVED** [review]
lgtm

**Review by hegerj — APPROVED** [review]

**Pull request merged**
