### PR TITLE
Convert the report step into dynamic plugins

### PR DESCRIPTION
**Pull request by psss**
Implement common classes Report and ReportPlugin.
ReportDisplay plugin with summary and test list.
Include a basic test for correct report summary.

### CODE REVIEW

**Comment by pvalena** [comment]
@psss to me this changes look mostly same as in https://github.com/psss/tmt/pull/230. Is that intended? You probably want me to review only the second commit, right?

**Comment by pvalena** [comment]
WRT only the second commit it LGTM.

**Comment by thrix** [comment]
@psss also report on not run plan looks weird:

```
(tmt) [mvadkert@freedom ~/git/github.com/tmt] (dynamic-report)$ tmt run -v report
3/var/tmp/tmt/run-048
Found 3 plans.

/plans/basic
summary: Essential command line features
    report
        how: display
        summary: 

/plans/helps
summary: Check help messages
    report
        how: display
        summary: 

/plans/smoke
summary: Just a basic smoke test
    report
        how: display
        summary: 
```

Maybe it could indicate `report` is empty or something ...

**Comment by psss** [comment]
Thanks for catching this. Dry mode for `local` provision fixed (will need some more care to work across all plugins, but let's track that in a different issue or pull request) and `no results` message added.

**Comment by psss** [comment]
@TomasTomecek, @lachmanfrantisek, could you please have a look?

    pods \"docker-io-usercont-sandcastle-20200507-111349983158\" is forbidden: exceeded quota

Thanks.

**Pull request merged**
