### PR TITLE
minute: Add right network id as 1minutetip uses.

### PR DESCRIPTION
**Pull request by RHEmployee**

### CODE REVIEW

**Comment by psss** [comment]
After @FrNecas fixed the IPv4 parsing in #543 the `minute` provision works just fine for me. @RHEmployee, why do you propose this change? I'm not sure hard-coding a specific value is a better approach.

**Comment by RHEmployee** [comment]
> After @FrNecas fixed the IPv4 parsing in #543 the `minute` provision works just fine for me. @RHEmployee, why do you propose this change? I'm not sure hard-coding a specific value is a better approach.
Hi. Because it's how 1minutetip and 1minutetip instances works. We have specified network with some minor configuration changes and we just forcing instances to use it.

Feel free to close this but I really don't understand what this module should do... mimic 1minutetip?

**Comment by RHEmployee** [comment]
> I'm not sure hard-coding a specific value is a better approach.
also "parsing" 1minutetip bash script doesn't seem to be good approach ;-P. But who Am I to judge? :)

self.debug(f"Get the API URL from '{SCRIPT_PATH}'.")
script_content = self.read(SCRIPT_PATH)
match = re.search(API_URL_RE, script_content)

**Comment by psss** [comment]
> Feel free to close this but...

@FrNecas, what do you think?

> I really don't understand what this module should do... mimic 1minutetip?

Implement one of the provision methods so that you can choose if you want to run tests on your localhost, in a container, vm, openstack...

> also "parsing" 1minutetip bash script doesn't seem to be good approach ;-P

Do you have a better proposal how to prevent disclosing the internal url?

**Comment by FrNecas** [comment]
Is there a reason why the specific network is used in 1minutetip? Does it work differenly from the others? The solution currently used was proposed by @thrix and I think it makes sense to use the network that is used the least to avoid potential problem with overloading a network but I am definitely not an expert on such things, let alone on openstack :) I've tested several networks and they seem to work just fine after fixing the regex.

Parsing the URL from 1minutetip script is a temporary workaround we made when implementing the plugin. Ideally, we would later create a config and we could distribute the config with the correct internal URL inside Red Hat so that `tmt run provision -h minute` would work out of the box without any additional setup. This solution seemed like the best at the time as potential users of this plugin already use 1minutetip so parsing it from the script covers most use-cases for now but it is far from ideal.

**Comment by RHEmployee** [comment]
> Do you have a better proposal how to prevent disclosing the internal url?

Yeah.. everything is better than "parsing" internal bash script.
For example 2 level configuration would be nice.
One can be distributed with internal tools and have know place. We can call it presets.
Then there will be second config file in user directory, which is able to overload presets.

If nothing provided, you can fallback to heuristic based on magic.


> Is there a reason why the specific network is used in 1minutetip? Does it work differently from the others?
No. It doesn't matter. It's just random string which I liked... magic numbers....

And Now for Something Completely Different

I don't know how others networks behave. But I know how this specific network behaves and it's enough for me.
It matters in case if you want to guarantee at least something to users. 
Provide working ipv6 for example. Or I remember how specially configured this network to allow ingress and egress. IPv4 ranges are also with sync with documentation for user's ssh configuration.
provider_net_cci_2 have ipv6 configured (there is ticket for covering even dns names...) etc...

If you call it minute then should it behave like 1minutetip?

**Comment by thrix** [comment]
There are multiple networks in PSI Openstack which provide also IPv6. If we want to choose networks with IPv6, we should still guess them :) We do not want to hardcode anything.  We have been there. It would be wise from 1minutetip to guess the network, or it might just randomly break once the network is full :) And no, we do not want to be really 100% compatible with whatever 1minutetip does, we just use it to easily provision machines on internal Openstack.

**Comment by RHEmployee** [comment]
Ok. How I wrote in previous comment, I need to guarantee at least something for more or less stable and predictable testing environment. If this is not in aim of tmt/minute then ok. Closing.

Minute name is totally confusing. In case of onboarding 1minutetip users, it would just create chaos.

**Comment by RHEmployee** [comment]
Additional notes:
> We have been there. It would be wise from 1minutetip to guess the network, or it might just randomly break once the network is full :)
Huh?
Instances and free address space is something 1 to 1. So if you are out of ip address space then you don't have enough instances. I need to guarantee for example ipv6 address space so guessing random networks without ingress/engress set as I expect is nonsense.

About hardcoding: I proposed different solution with using 2 level configuration but without notice nor any response.

**Comment by psss** [comment]
> About hardcoding: I proposed different solution with using 2 level configuration but without notice nor any response.

I think the first step here could be to create an internal package with the plugin, as suggested by @FrNecas. That could contain the default config. @RHEmployee, are you possibly interested in working on this?

**Comment by thrix** [comment]
> Additional notes:
> 
> > We have been there. It would be wise from 1minutetip to guess the network, or it might just randomly break once the network is full :)
> 
> Huh?
> Instances and free address space is something 1 to 1. So if you are out of ip address space then you don't have enough instances. 

Instances in Openstack? That is not true, those resources are orthogonal. We hit no IP address on a network and had plenty of openstack instances available ...

> I need to guarantee for example ipv6 address space so guessing random networks without ingress/engress set as I expect is nonsense.

Not sure I follow, you can find the most suitable (with most free IPv4 addresses) network with support for both IPv4 and IPv6.

> 
> About hardcoding: I proposed different solution with using 2 level configuration but without notice nor any response.

We have a solution to choose the correct network, there is no need for any other solution.

**Comment by thrix** [comment]
> > About hardcoding: I proposed different solution with using 2 level configuration but without notice nor any response.
> 
> I think the first step here could be to create an internal package with the plugin, as suggested by @FrNecas. That could contain the default config. @RHEmployee, are you possibly interested in working on this?

I believe the current way of things is correct, we can just make sure we choose a network with also IPv6 enabled?

**Comment by FrNecas** [comment]
I think we could add an option to the plugin that would force IPv6-enabled network, how about that? Or perhaps it could be the default and then add option to allow networks without IPv6? Although I am not sure how to check if the network is IPv6-enabled, will have to find out how to do that :)

**Pull request closed without merging**
