### PR TITLE
Allow to print fmf identifier in tmt tests show

### PR DESCRIPTION
**Pull request by lukaszachy**
Use `tmt tests show --fmf-id`

### CODE REVIEW

**Comment by lukaszachy** [comment]
@psss  Where should this option be documented?

**Comment by psss** [comment]
> @psss Where should this option be documented?

I would add it to the [test examples](https://tmt.readthedocs.io/en/latest/examples.html#explore-tests) section.

**Comment by lukaszachy** [comment]
Updated, please check

**Comment by psss** [comment]
Thanks for the improvement. I thought the extra option is needed in order to provide a pipe-able output, for example something like that:

    wow --fmf-id=$(tmt tests show /tests/docs --fmf-id)

If this is just an extension of the output, what about adding the fmf id to the verbose output (with the same color as the `sources` line)? Or we could support both.

**Comment by lukaszachy** [comment]
You are right, but I find `tmt tests show /tests/docs --fmf-id` confusing, as enable 'details' but limit them to single value? Not to mention you would need to write just fmf-id to stdout to make pipe works.

Is there option for machine readable output format?

**Comment by lukaszachy** [comment]
I made it part of verbose, please review @psss

**Comment by psss** [comment]
Thanks, looks good. Will merge with just a minor adjustments. Regarding the machine readable output: For now there's just the `tmt test export`. We can extend to make it more flexible in the future.

**Pull request merged**
