### PR TITLE
Make sure we run finish always

### PR DESCRIPTION
**Pull request by thrix**
I believe finish step, if enabled, should run always,
even in case of errors.

This way container/VMs will be nicely stopped after the run.

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

### CODE REVIEW

**Comment by pvalena** [comment]
Also, is it posible to do ```tmt run -a --without finish```; or at least **on error**?

**Comment by thrix** [comment]
> Seems good.
> 
> Do I understand correctly that if user enumerates the steps (not using `--all`), the finish won't be run?
> 
> f.e.
> 
> ```
> tmt run discover prepare
> ```
> 
> won't run `finish`, right?

Yes, it should not run finish ... as before ....

**Comment by thrix** [comment]
> Also, is it posible to do `tmt run -a --without finish`; or at least **on error**?

No that is not possible, I do not think we need to address this for now, seems like a common use case ...

**Comment by psss** [comment]
Nice enhancement! Thanks. Merging with a minor adjustment 0632a75.

**Pull request merged**
