### PR TITLE
Support enabling/disabling plans and stories

### LINKED ISSUE #141: Documentation incorrect on "enabled:" attribute
I noticed the documentation https://tmt.readthedocs.io/en/latest/spec/tests.html says the enabled attribute can be either "yes" or "no" but tmt test convert actually creates "enabled: true" and the console output says "enabled: True" with a capital "T" 
It should probably all be the same to avoid confusion.

### PR DESCRIPTION
**Pull request by psss**
Move 'enabled' to the core attributes (L0 metadata).
Update the specification to cover all metadata levels.
Disable plans needing special setup by default.
Add test coverage for selecting/showing tests/plans/stories.
Use the canonical form for showing boolean (resolves #141).

### CODE REVIEW

**Comment by psss** [comment]
This is quite an important feature, let's try to squeeze this into 1.4 as well.

**Review by FrNecas — APPROVED** [review]
LGTM, works as expected

**Comment by psss** [comment]
Thanks for the review & testing!

**Pull request merged**
