### PR TITLE
Explicit mention '.' as special value for names

### PR DESCRIPTION
**Pull request by lukaszachy**
Currently usage just says [REGEXP] and '.' is mentioned bellow in the text.

### CODE REVIEW

**Comment by psss** [comment]
Looks good. Shall we modify the remaining two `REGEXP` occurences as well to make the usage messages consistent? The functionality is the same for `tmt run plans --name` and `tmt run tests --name`.

**Comment by lukaszachy** [comment]
I'm not sure, because it's not mentioned in the usage, just as a placeholder variable name.
However I see that ` -n, --name REGEXP     Regular expression to match plan name.` doesn't mention '.' while text above it does.

**Comment by lukaszachy** [comment]
@psss pushed. Feel free to edit to make more sense.

**Review by psss — APPROVED** [review]
Thanks for covering the `tmt run tests/plans` part as well. I've just applied the same `[REGEXP|.]` example to make the help usage conistent. Rebased and squashed.

**Pull request merged**
